<h3 class="block">Confirmar widgetss </h3>
<h4 class="form-section">1.1. Datos del Puesto</h4>
<div class="form-group">
    <label class="control-label col-md-3">Nro de Item <span class="required"> * </span>
    </label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="id_nro_item"></p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">Nivel <span class="required"> * </span>
    </label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="id_nivel"></p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">Categoría <span class="required"> * </span>
    </label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="id_categoria"></p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">Denominación del cargo <span class="required"> * </span>
    </label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="id_cargo"></p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">Denominación del puesto <span class="required"> * </span>
    </label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="id_puesto"></p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">Dependencia <span class="required"> * </span>
    </label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="id_dependencia"></p>
    </div>
</div>

<h4 class="form-section">1.2. Relaciones del Puesto</h4>
<div class="form-group">
    <label class="control-label col-md-3">Depende de <span class="required"> * </span>
    </label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="id_depende_de"></p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">Supervisa a <span class="required"> * </span>
    </label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="supervisa_1"></p>
    </div>
</div>
<hr>
<h4 class="form-section">2.2. Normas Generales a cumplir</h4>
<div class="form-group">
    <label class="control-label col-md-3">1.</label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="form_control_ng_1">
        </p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">2.</label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="form_control_ng_2">
        </p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">3.</label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="form_control_ng_3">
        </p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">4.</label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="form_control_ng_4">
        </p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">5.</label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="form_control_ng_5">
        </p>
    </div>
</div>
<hr>
<h4 class="form-section">2.2. Normas Especificas a Cumplir</h4>
<div class="form-group">
    <label class="control-label col-md-3">1.</label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="form_control_ne_1">
        </p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">2.</label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="form_control_ne_2">
        </p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">3.</label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="form_control_ne_3">
        </p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">4.</label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="form_control_ne_4">
        </p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">5.</label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="form_control_ne_5">
        </p>
    </div>
</div>

<hr>
<div class="form-group">
    <label class="control-label col-md-3">Fullname:</label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="fullname">
        </p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">Gender:</label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="gender">
        </p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">Phone:</label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="phone">
        </p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">Address:</label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="address">
        </p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">City/Town:</label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="city">
        </p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">Country:</label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="country">
        </p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">Remarks:</label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="remarks">
        </p>
    </div>
</div>
<h4 class="form-section">Billing</h4>
<div class="form-group">
    <label class="control-label col-md-3">Card Holder Name:</label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="card_name">
        </p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">Card Number:</label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="card_number">
        </p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">CVC:</label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="card_cvc">
        </p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">Expiration:</label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="card_expiry_date">
        </p>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3">Payment Options:</label>
    <div class="col-md-4">
        <p class="form-control-static" data-display="payment[]">
        </p>
    </div>
</div>