<?php echo $this->partial('partial/form-partial', array('form' => $this->form, 'error_en_formulario' => $this->error_en_formulario)); ?>

<!--<div class="modal-header">-->
<!--    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>-->
<!--    <h4 class="modal-title">"--><?php //echo $tabla->getNombre(); ?><!--" - Crear Registro</h4></div>-->
<!--<div class="modal-body">-->
<!--</div>-->

<?php //echo $this->widgetModel ?>

<script src="/assets/admin/layout/scripts/form-validation.js"></script>
<!-- END PAGE LEVEL STYLES -->
<script>
    jQuery(document).ready(function () {

        var parametros = {
            div_render_callback: '.page-content-body',
            form_name: "formEstados"
        };

        FormValidation.init(parametros);
    });
</script>


