<div class="row">
<ul class="page-breadcrumb breadcrumb">
	<li>
		<i class="fa fa-home"></i>
		<a href="<?php echo $this->url('administracion/default', array('controller' => 'index', 'action' => 'index')); ?>">
			Inicio
		</a>
	</li>
</ul>
</div>


<div class="row">
	<div class="col-md-3">
		<img src="/images/logo.jpg" class="img-responsive" />
	</div>
	<div class="col-md-9 text-right">
		<h1>Bienvenido al</h1>
		<h3>Sistema Inform&aacute;tico de Calificaci&oacute;n de A&ntilde;os de Servicio</h3>
	</div>
</div>
