<div class="portlet-body">

    <div class="table-responsive">
        <!--<table class="table table-striped table-bordered table-hover table-full-width" id="dataTables_generico">-->
        <table class="table table-bordered table-hover" id="dataTables_generico">
            <thead>
            <tr  role="row" class="label-info" style="color: blue; background-color: #EEE;">
                <?php foreach ($this->cabecera as $value): ?>
                    <th class="text-center"><?php echo $value; ?></th>
                <?php endforeach; ?>
                <th class="text-center">ACCIONES</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->listado as $value): ?>
                <tr>
                    <?php foreach ($this->dato as $val): ?>
                        <td  class="text-center">
                            <?php eval("echo $val"); ?>
                        </td>
                    <?php endforeach; ?>
                    <td class="text-center">
                        <?php echo $this->partial('administracion/index/partial_td_list',array('value'=>$value,'clase_id' => $this->id)); ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<!-- Page-Level Demo Scripts - Tables - Use for reference -->

<script src="/assets/global/plugins/select2/select2.min.js" type="text/javascript" ></script>
<script>
  //  $(document).ready(function() {

        jQuery(document).ready(function () {




            var initTable1 = function () {

                var table = $('#dataTables_generico');

                // begin first table
                var oTable = table.dataTable({

                    // Internationalisation. For more info refer to http://datatables.net/manual/i18n
                    /* "language": {
                     "aria": {
                     "sortAscending": ": activate to sort column ascending",
                     "sortDescending": ": activate to sort column descending"
                     },
                     "emptyTable": "No data available in table",
                     "info": "Showing _START_ to _END_ of _TOTAL_ entries",
                     "infoEmpty": "No entries found",
                     "infoFiltered": "(filtered1 from _MAX_ total entries)",
                     "lengthMenu": "Show _MENU_ entries",
                     "search": "Search:",
                     "zeroRecords": "No matching records found"
                     },*/



                    // Uncomment below line("dom" parameter) to fix the dropdown overflow issue in the datatable cells. The default datatable layout
                    // setup uses scrollable div(table-scrollable) with overflow:auto to enable vertical scroll(see: assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js).
                    // So when dropdowns used the scrollable div should be removed.
                    //"dom": "<'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r>t<'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>",
                   // "dom": "<'row'<'col-md-8 col-sm-12'pli><'col-md-4 col-sm-12'<'table-group-actions pull-right'>>r><'table-scrollable't><'row'<'col-md-8 col-sm-12'pli><'col-md-4 col-sm-12'>>", // datatable layout
                    "bStateSave": true, // save datatable state(pagination, sort, etc) in cookie.

                    /*"columns": [
                        {"orderable": true},
                        {"orderable": true},
                        {"orderable": false},
                        {"orderable": false},
                        {"orderable": false},
                        {"orderable": false},
                        {"orderable": false}
                    ],*/
                    "lengthMenu": [
                        [5, 10, 15, 20, -1],
                        [5, 10, 15, 20, "Todos"] // change per page values here
                    ],
                    // set the initial value
                    "pageLength": 10,
                    "pagingType": "bootstrap_full_number",
                    /*"language": {
                     "search": "Buscar: ",
                     "lengthMenu": "  _MENU_ registros",
                     "paginate": {
                     "previous":"Atras",
                     "next": "Siguiente",
                     "last": "Ultimo",
                     "first": "Primero"
                     }
                     },*/




                    "columnDefs": [{  // set default column settings
                        'orderable': false,
                        'targets': [0]
                    }],


                    "order": [
                        [0, "asc"]
                    ] // set first column as a default sort by asc
                });


                var tableWrapper = $('#dataTables_generico_wrapper');

                /*
                table.find('.group-checkable').change(function () {
                    var set = jQuery(this).attr("data-set");
                    var checked = jQuery(this).is(":checked");
                    jQuery(set).each(function () {
                        if (checked) {
                            $(this).attr("checked", true);
                            $(this).parents('tr').addClass("active");
                        } else {
                            $(this).attr("checked", false);
                            $(this).parents('tr').removeClass("active");
                        }
                    });
                    jQuery.uniform.update(set);
                });
                */

               // table.on('change', 'tbody tr .checkboxes', function () {
                 //   $(this).parents('tr').toggleClass("active");
               // });



               // tableWrapper.find('.dataTables_length select').addClass("form-control input-xsmall input-inline"); // modify table per page dropdown


                //jQuery('#dataTables_generico_wrapper .dataTables_filter input').addClass("form-control input-small input-inline"); // modify table search input
                //jQuery('#dataTables_generico_wrapper .dataTables_length select').addClass("form-control input-small"); // modify table per page dropdown
                $('#dataTables_generico_wrapper .dataTables_length select').select2(); // initialize select2 dropdown

                /*$('#dataTables_generico_column_toggler input[type="checkbox"]').change(function(){
                    // Get the DataTables object again - this is not a recreation, just a get of the object
                    var iCol = parseInt($(this).attr("data-column"));
                    var bVis = table.fnSettings().aoColumns[iCol].bVisible;
                    table.fnSetColumnVis(iCol, (bVis ? false : true));
                });*/

                tableWrapper.find('.dataTables_length select').select2(); // initialize select2 dropdown

            }

            //Datatable.init();
            if (!jQuery().dataTable) {
                return;
            }

           // alert('entro');
            initTable1();


        });



        /*
        var oTable = $('#dataTables_generico').dataTable({
            "sPaginationType": "bootstrap",
            "aoColumnDefs": [
                { "aTargets": [ 0 ] }
            ],
            "aaSorting": [[0, 'desc']],
            "bStateSave": true,
            "oLanguage": {
                "sLengthMenu": "_MENU_ registros por página",
                "sSearch": "Buscar: _INPUT_",
                "sInfo": "Mostrando _START_ a _END_ registros de _TOTAL_ entradas",
                "sInfoFiltered": " - filtrado _MAX_ registros totales",
                "sInfoEmpty": "Sin entradas para mostrar",
                "sEmptyTable": "Datos no disponibles en esta tabla"
// 				  	"sPaginate": {
//      	       			"iStart": "Primero",
//      	       			"last": "Ultimo",
//      	       			"next": "Siguiente",
//      	       			"previous": "Anterior"
//      	       	   	}
            },
            "aLengthMenu": [
                [10, 15, 20, -1],
                [10, 15, 20, "Todos"] // change per page values here
            ],
            "iDisplayLength": 10

        });
        jQuery('#dataTables_generico_wrapper .dataTables_filter input').addClass("form-control input-small input-inline"); // modify table search input
        jQuery('#dataTables_generico_wrapper .dataTables_length select').addClass("form-control input-small"); // modify table per page dropdown
        jQuery('#dataTables_generico_wrapper .dataTables_length select').select2(); // initialize select2 dropdown

        $('#dataTables_generico_column_toggler input[type="checkbox"]').change(function(){
            // Get the DataTables object again - this is not a recreation, just a get of the object
            var iCol = parseInt($(this).attr("data-column"));
            var bVis = oTable.fnSettings().aoColumns[iCol].bVisible;
            oTable.fnSetColumnVis(iCol, (bVis ? false : true));
        });*/
    //});



</script>