<?php echo $this->doctype(); ?>

<html lang="es">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('MEFP - SEGURIDAD')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo-mefp-transp.png'))
        //->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
    ?>
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        // ->prependFile($this->basePath() . '/js/application.js')
    ; ?>

    <?php //echo YsConfigAssets::includeAssets("*") ?>

<style>
    body{
        background-color: rgba(187, 234, 255, 0.36);
    }

</style>

</head>
<body>
<div class="container">
    <?php //echo $this->partial('layout/partial-nav-bar', array('valor' => '')); ?>
    <?php //echo $this->partial('layout/partial-header', array('search' => false)); ?>
    <?php //echo $this->partial('layout/partial-menu', array('valor' => '')); ?>
    <?php //echo $this->partial('layout/partial-breadcrumb', array('valor' => '')); ?>

    <br/><br/>
    <div class="row">
        <div class="col-md-4" ></div>
        <div class="col-md-4" align="center">
            <img src="/img/logo_mefp_2016.png" class="img-responsive"
                 alt="Logo MEFP" style="max-width: 100%; height: auto; padding: 10px 0 15px 0">
            <div id="content" align="left">
                <?php echo $this->content; ?>
            </div>
        </div>
        <div class="col-md-4" ></div>
    </div>
    <?php //echo $this->partial('layout/partial-footer', array('valor' => '')); ?>

    <noscript>
        <div align="center" style="color: red">
            ¡Advertencia! JavaScript debe estar habilitado para un correcto funcionamiento de la Aplicaci&oacute;n.
        </div>
    </noscript>
</div>
<!--<script src="/assets/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>-->
<script>
    jQuery(document).ready(function() {
       // if ($.cookie) {
        //    $.cookie('option-menu', null);
            // $.cookie('option-menu-prin', option);
        //}
    });
</script>
</body>
</html>
