<div id="result">
    <div class="row">
        <div class="col-md-12">
            <!-- <h3 class="page-title">
                 Configuracion -
                 <small>Administración de Parametros</small>
             </h3>-->


<!--            <div class="">
                <h3 class="title">
                    <b>Formulacion POAI - ITEMS</b>
                </h3>
            </div>-->

            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption">
                        AREA ORGANIZACIONAL:
                    </div>

                    <!-- BEGIN BOTON NUEVO -->
                    <div class="actions">
                        <div class="btn-group btn-group-xs">
                            <a href="<?php echo $this->url('formulacion/default', array('controller' => 'index', 'action' => 'nuevo','id' => '0')); ?>"
                               data-target="#modal_nuevo"
                               data-toggle="modal"
                               class="btn btn-info yellow">
                                <i class="fa fa-file-text"></i> Nuevo Registro
                            </a>

                            <a class="btn btn-primary" href="#" data-toggle="dropdown">
                                Columnas <i class="fa fa-angle-down"></i>
                            </a>
                            <div id="tbl_items_column_toggler" class="dropdown-menu hold-on-click dropdown-checkboxes pull-right">
                                <label><input type="checkbox" checked data-column="0"> Escala</label>
                                <label><input type="checkbox" checked data-column="1"> Item</label>
                                <label><input type="checkbox" checked data-column="2"> Cargo</label>
                                <label><input type="checkbox" checked data-column="3"> Puesto</label>
                                <label><input type="checkbox" checked data-column="4"> Acciones</label>

                            </div>
                        </div>
                    </div>
                    <!-- END BOTON NUEVO -->
<!--                    <br>
                    <br>
                    <br>
                    <div class="row" style="font-size: 12px">
                        <div class="col-md-2"></div>
                        <div class="col-md-10">
                            <table class="table table-bordered">
                                <tbody>
                                <tr id="filter_global">
                                    <td style="margin: 0px;" align="left">BUSCAR:</td>
                                    <td style="margin: 0px;" align="right">Por Gestion</td>
                                    <td style="padding: 0px;" align="left" id="gestionFilter"></td>
                                    <td style="margin: 0px;" align="right">Por Estado</td>
                                    <td style="padding: 0px;" align="left" id="miEstadoFilter"></td>
                                </tr>
                                </tbody>
                            </table>
                        </div>

                    </div>-->


                </div>
                <div class="portlet-body">

                    <!--  INICIO DE TABLA DE BASES DE DATOS-->
                    <table class="table  table-hover table-bordered  table-condensed" id="tbl_items" style="font-size: 10px;" width="100%">
                        <thead>
                        <tr style="color: Menu; background-color: #3799dc;">
                            <th class="text-center" style="width: 5%;">Escala</th>
                            <th class="text-center" style="width: 10%;">Item</th>
                            <th class="text-center" style="width: 20%;">Cargo</th>
                            <th class="text-center" style="width: 40%;">Puesto</th>
                            <th class="text-center" style="width: 20%;">Acciones</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr style="background-color: #3799dc; display: none">
                            <th class="text-center">Nro</th>
                            <th class="text-center">Nro</th>
                            <th class="text-center">--TODOS--</th>
                            <th class="text-center">Periodo</th>
                            <th class="text-center">Acciones</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        <?php foreach ($listadoItems as $registro):

                            $detalle = "Cargo: " . $registro['cargo'] . "<br>".
                                        "Puesto:" .$registro['puesto'] . "<br>".
                                        "Asignado: " .$registro['paterno']." ".$registro['materno']." ".$registro['nombres'];

                            ?>
                            <tr>
                                <td class="text-center"><?php echo $registro['escala_nivel'] ?></td>
                                <td class="text-center"><?php echo $registro['item'] ?></td>
                                <td class="text-left"><?php echo $registro['cargo'] ?></td>
                                <td class="text-left">
                                    <?php echo $registro['puesto'] ?>
                                    <br>
                                    [<i>Asignado a: <?php echo $registro['paterno']." ".$registro['materno']." ".$registro['nombres'] ?></i>]
                                </td>

                                <td class="text-center">
                                    <a href="<?php echo $this->url('formulacion/default', array('controller' => 'index', 'action' => 'poai', 'id' => 1, 'id2' => $registro['id_persona'], 'id3' => $this->idUnidad )); ?>"
                                       class=" btn btn-xs green"
                                       data-target="#modal_nuevo" data-toggle="modal"
                                       title="Ver Formulario" style="font-size: 10px;">
                                        <i class="fa fa-building"></i>
                                    </a>
                                    <button class="btn red btn-xs btn-circle" type="button"
                                            title=""
                                            onclick="openModalPoai(1,<?php echo $registro['id_persona']; ?>,<?php echo $this->idUnidad; ?>)">
                                        <i class="fa fa-file-pdf-o"></i> PDF
                                    </button>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                    <!-- FIN DE TABLA DE BASES DE DATO-->


                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>

    </div>
    <!--  BEGIN CONTENIDO-->



<!--  BEGIN CONTENIDO-->
<!--  BEGIN MODAL-->
<div class="modal fade" id="modal_nuevo" tabindex="-1" role="basic" aria-hidden="true" data-backdrop="static" data-keyboard="true">
    <div class="modal-dialog modal-full">
        <div class="modal-content">
        </div>
    </div>
</div>
<!--  END MODAL-->

</div>

<script>

    function openModalPoai(idGp,idPersona,idUnidad){

        var url = '/formulacion/index/poai/'+idGp+'/'+idPersona+'/'+idUnidad;

        var modalContent = $('.modal-content');
        //var pageContentBody = "";
        Metronic.startPageLoading();
        $.ajax({
            type: "GET",
            cache: false,
            url: url,
            dataType: "html",
            success: function (res) {//console.log(res);
                Metronic.stopPageLoading();
                modalContent.html(res);
                //pageContentBody = res;
                Layout.fixContentHeight(); // fix content height
                Metronic.initAjax(); // initialize core stuff
            },
            error: function (xhr, ajaxOptions, thrownError) {
                console.log(xhr);
                console.log(ajaxOptions);
                console.log(thrownError);
                modalContent.html('<h4>Could not load the requested content.</h4>');
                Metronic.stopPageLoading();
            }
        });

        var html =
            '<div class="modal-header label-default">' +
            //'<div class=""><i class="fa fa-windows"></i> PDF</div>' +
            //'<div class="" style="text-align:right;"><button type="button" data-dismiss="modal" class="btn blue btn-xs"><i class="fa fa-times"></i>   Cerrar </button></div>' +
            '<button type="button" class="close" data-dismiss="modal"> Cerrar</button>'+
            '<div class="caption"><i class="fa fa-windows"></i> Vista Previa: </div>'+
            '</div>' +
            '<div class="modal-body">' + modalContent +
                //'<div id="div-content-modal-body"></div>' +
            '</div>'+
            '<div class="modal-footer label-default">'+
            '<button class="btn btn-xs blue" type="button" data-dismiss="modal"><i class="fa fa-times"></i> Cerrar</button>'+
            '</div>';

        //console.log(pageContentBody);

       // $('.modal-content').html(html);
        $('#modal_nuevo').modal('show');








        //var url = '/data/'+id+'_parametro.pdf';
        //window.showModalDialog(url,null, "dialogWidth:900px; dialogHeight:500px;dialogLeft:150;dialogTop:50;");
    }


    jQuery(document).ready(function () {
        var initTable1 = function () {

            var oTable = $('#tbl_items');

            var cabeceraImpresion =
                "<div class='text-left' style='font-size: 1.2em'>" +
                    "<span><b>MINISTERIO DE ECONOMIA Y FINANZAS PUBLICAS</b></span>" +
                    "<br><span><?php echo \MisLibrerias\DatosSesion::getAplicacion() ?></span>" +
                    "<br><span>ADMINISTRACION DE PERIODOS</span>" +
                    "<br><span>REPORTE AL <?php echo date("d-m-Y")?></span>" +
                "</div>";
            var cabeceraImpresionXls =
                "MINISTERIO DE ECONOMIA Y FINANZAS PUBLICAS" +
                    "\n<?php echo \MisLibrerias\DatosSesion::getAplicacion() ?>" +
                    "\nADMINISTRACION DE PERIODOS" +
                    "\nREPORTE AL <?php echo date("d-m-Y")?>\n";

            // begin first table
            oTable.dataTable({
                //dom: 'T<"clear">lfrtip',
                //dom: 'T<"clear">lfrtip<"clear spacer">T',
                tableTools: {
                    "sSwfPath":  "/assets/global/plugins/datatables/extensions/TableTools/swf/copy_csv_xls_pdf.swf",

                    "aButtons": [

                       // "select",
                        //"print",
                        //{
                        //    "sExtends":    "collection",
                        //    "sButtonText": "Save",
                    //    "aButtons":    [ "csv", "xls", "pdf" ]
                        //},

                        {
                            "sExtends": "xls",
                            "sButtonText": "Exportar a Excel",
                            "sMessage": cabeceraImpresionXls,
                            "mColumns": "orderable",
                            "sFileName": "Periodo_<?php echo date('d-m-Y')?>.csv",
                            "oSelectorOpts": {
                                page: 'all'
                            },
                            "fnClick": function( nButton, oConfig, flash ) {
                                this.fnSetText( flash,  oConfig.sMessage +"\n"+ this.fnGetTableData(oConfig) );
                            }
                        },

                        {
                            "sExtends":    "print",
                            "sButtonText": "Imprimir",
                            "sInfo":  "",
                            "bShowAll": true,
                            //"hidden": [true,true,true,false,false],
                            "sMessage": cabeceraImpresion,
                            //"mColumns": "orderable",
                            "fnClick": function( button, conf ) {
                                this.fnPrint( true, conf);
                                window.print();
                                //window.close();
                                this.fnPrint( false, conf);
                            }
                        },



                    ]

                },

                // Uncomment below line("dom" parameter) to fix the dropdown overflow issue in the datatable cells. The default datatable layout
                // setup uses scrollable div(table-scrollable) with overflow:auto to enable vertical scroll(see: assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js).
                // So when dropdowns used the scrollable div should be removed.
                //"dom": "<'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r>t<'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>",

                 //"bStateSave": true, // save datatable state(pagination, sort, etc) in cookie.

                "columns": [
                  {"visible": true},
                  {"visible": true},
                  {"visible": true},
                  {"visible": true},
                  {"visible": true},
                 ],
                "lengthMenu": [
                    [5, 10, 15, 20, -1],
                    [5, 10, 15, 20, "Todos"] // change per page values here
                ],
                // set the initial value
                "pageLength": 5,
                "pagingType": "bootstrap_full_number",

                /*"language": {
                    //url: 'http://cdn.datatables.net/plug-ins/3cfcc339e89/i18n/Spanish.json'
                   // url: '/assets/global/plugins/datatables/plugins/bootstrap/es_ES.txt'
                },*/

                "columnDefs": [
                    { 'orderable': true,'targets': [0]},
                    { 'orderable': true,'targets': [1]},
                    { 'orderable': true,'targets': [2]},
                    { 'orderable': true,'targets': [3]},
                    { 'orderable': false,'targets': [4]},
                ],

                "order": [
                    [0, "asc"],[1, "asc"]
                ],
                bFilter : true,
            }).columnFilter({aoColumns:[
                    null,
                    null,
                    { type: "select",sSelector: "#unidadFilter" },
                    null,
                ]}
            );

            var tableWrapper = jQuery('#tbl_items_wrapper');
            tableWrapper.find('.dataTables_length select').select2(); // initialize select2 dropdown
            jQuery('#tbl_items_wrapper .dataTables_filter input').addClass("form-control input-small input-inline"); // modify table search input
           // jQuery('#filter_global .select_filter').select2();
           // jQuery('#filter_global .select_filter').addClass("form-control select_filter_custom"); // modify table per page dropdown
             tableWrapper.find('.dataTables_length select').addClass("form-control input-small input-inline"); // modify table per page dropdown

            $('#tbl_items_column_toggler input[type="checkbox"]').change(function(){
                /* Get the DataTables object again - this is not a recreation, just a get of the object*/
                var iCol = parseInt($(this).attr("data-column"));
                var bVis = oTable.fnSettings().aoColumns[iCol].bVisible;
                oTable.fnSetColumnVis(iCol, (bVis ? false : true));
            });


/*            var tt = new $.fn.dataTable.TableTools( table );
            $( tt.fnContainer() ).insertBefore('div.dataTables_wrapper');*/

        }

        if (!jQuery().dataTable) {
            return;
        }

        initTable1();
    });


    jQuery(document).ready(function () {

        $('#tbl_items').on('click', '#cambiar_estado', function (e) {

            var pageContentBody = $('.page-content .page-content-body');

            var id = $(this).attr("data-id");
            var url_callback = jQuery(this).attr("data-url-callback");
            var url = jQuery(this).attr("data-url");
            e.preventDefault();
            Metronic.startPageLoading();
            $.ajax({
                url: url,
                data: {id: id},
                type: 'GET',
                async: false,
                dataType: "json",
                success: function (data) {
                    Metronic.stopPageLoading();
                    if (data.respuesta) {
                        Metronic.startPageLoading();
                       //jQuery('.page-content-body').load(url_callback);
                        //pageContentBody.load(url_callback);
                        //jQuery('#result').load(url_callback);
                        jQuery('.page-content .page-content-body').load(url_callback);
                        Metronic.stopPageLoading();
                        toastr.success(data.mensaje, 'SUCCESS');
                    } else {
                        toastr.error(data.mensaje, 'ERROR');
                    }
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    toastr.error('OCURRIÓ UN ERROR AL EJECUTAR LA PAGINA', 'ERROR');
                    Metronic.stopPageLoading();
                }
            });

        });


        $('#tbl_items').on('click', '#eliminar', function (e) {

            var id = $(this).attr("data-id");
            var url_callback = jQuery(this).attr("data-url-callback");
            var url = jQuery(this).attr("data-url");
            bootbox.setDefaults({
                locale: "es",
                title: "Confirmación"
            });
            bootbox.confirm("ESTA SEGURO QUE DESEA ELIMINAR EL REGISTRO?", function (result) {
                if (result) {
                    e.preventDefault();
                    Metronic.startPageLoading();
                    $.ajax({
                        url: url,
                        data: {id: id},
                        type: 'GET',
                        async: false,
                        dataType: "json",
                        success: function (data) {
                            Metronic.stopPageLoading();
                            if (data.respuesta) {
                                Metronic.startPageLoading();
                                //jQuery('.page-content-body').load(url_callback);
                                jQuery('.page-content .page-content-body').load(url_callback);
                                Metronic.stopPageLoading();
                                toastr.success(data.mensaje, 'SUCCESS');
                            } else {
                                toastr.error(data.mensaje, 'ERROR');
                            }
                        },
                        error: function (xhr, ajaxOptions, thrownError) {
                            toastr.error('OCURRRIO UN ERROR AL EJECUTAR LA PAGINA', 'ERROR');
                            Metronic.stopPageLoading();
                        }
                    });
                }

            });


        });


    });


</script>

<style>
    /*.form-control{
        height: 2px;
        padding-bottom: 1px;
        padding-top: 1px;
    }*/
   /*  .select2-container
     .select2-choice{
        background-color: #eeeeee;
         height: 28px;
         padding-bottom: 5px;
         padding-top: 0px;
    }
    .select_filter_custom{
        font-size: 10px;
    }*/


</style>
