<?php echo $this->doctype(); ?>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="es">
<!--<![endif]-->
<head>
    <meta charset="utf-8"/>
    <title>MEFP | <?php echo \MisLibrerias\DatosSesion::getAplicacion() ?> </title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta content="Bonos Tesoro" name="description"/>
    <meta content="mefp-uti" name="author"/>
    <link href="/assets/global/css/fonts-googleapis.css" id="style_components" rel="stylesheet" type="text/css"/>
    <link href="/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/global/plugins/simple-line-icons/simple-line-icons.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/global/plugins/bootstrap/css/bootstrap.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/global/plugins/jquery-notific8/jquery.notific8.min.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/global/plugins/bootstrap-toastr/toastr.min.css" rel="stylesheet" type="text/css"/>

    <!--<link href="/assets/global/plugins/datatables/media/css/jquery.dataTables.css"  rel="stylesheet"  />
    <link href="/assets/global/plugins/select2/select2.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />
-->
    <!--<link rel="stylesheet" type="text/css" href="/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css"/>
    <link rel="stylesheet" type="text/css" href="/assets/global/plugins/datatables/media/css/jquery.dataTables.css">-->




    <link rel="stylesheet" type="text/css" href="/assets/global/plugins/select2/select2.css"/>
    <link rel="stylesheet" type="text/css" href="/assets/global/plugins/datatables/media/css/jquery.dataTables.css">



    <!--<link rel="stylesheet" type="text/css" href="/assets/global/plugins/datatables/extensions/Scroller/css/dataTables.scroller.min.css"/>-->
    <link rel="stylesheet" type="text/css" href="/assets/global/plugins/datatables/extensions/TableTools/css/dataTables.tableTools.min.css"/>


    <link rel="stylesheet" type="text/css" href="/assets/global/plugins/clockface/css/clockface.css"/>
    <link rel="stylesheet" type="text/css" href="/assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css"/>
    <link rel="stylesheet" type="text/css" href="/assets/global/plugins/bootstrap-timepicker/css/bootstrap-timepicker.min.css"/>
    <link rel="stylesheet" type="text/css" href="/assets/global/plugins/bootstrap-colorpicker/css/colorpicker.css"/>
    <link rel="stylesheet" type="text/css" href="/assets/global/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css"/>
    <link rel="stylesheet" type="text/css" href="/assets/global/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css"/>


    <!--<link rel="stylesheet" type="text/css" href="/assets/global/plugins/datatables/extensions/ColReorder/css/dataTables.colReorder.min.css"/>-->

    <link rel="stylesheet" type="text/css" href="/assets/global/plugins/jstree/dist/themes/default/style.min.css"/>

    <link href="/assets/global/css/components.css" id="style_components" rel="stylesheet" type="text/css"/>
    <link href="/assets/global/css/plugins.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/admin/layout/css/layout.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/admin/layout/css/themes/blue.css" rel="stylesheet" type="text/css" id="style_color" />
    <link href="/assets/admin/layout/css/custom.css" rel="stylesheet" type="text/css"/>
    <link rel="shortcut icon" href="favicon.ico"/>

    <!--<script type="text/javascript" language="javascript" src="/assets/global/plugins/jquery.min.js"></script>-->

</head>
<body class="page-header-fixed page-quick-sidebar-over-content">
<div class="page-header navbar navbar-fixed-top">
    <div class="page-header-inner">
        <div class="page-logo">
            <?php echo  $this->partial('layout/partials/partial-page-logo', array()); ?>
        </div>
        <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
        </a>
        <?php echo  $this->partial('layout/partials/partial-top-navigation-menu', array()); ?>
    </div>
</div>
<div class="clearfix"></div>
<div class="page-container">
    <div class="page-sidebar-wrapper">
        <?php echo  $this->partial('layout/partials/partial-page-sidebar', array('parametricas'=>$parametricas)); ?>
    </div>
    <div class="page-content-wrapper">
        <div class="page-content">
            <?php //echo  $this->partial('layout/partials/partial-page-header', array()); ?>
            <div class="page-content-body">
            <?php echo $this->content; ?>
            </div>
        </div>
    </div>
    <?php echo $this->partial('layout/partials/partial-page-quick-sidebar', array()); ?>
</div>
<div class="page-footer">
    <?php echo  $this->partial('layout/partials/partial-page-footer', array('date'=>date('Y'))); ?>
</div>
<!--[if lt IE 9]>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/respond.min.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/excanvas.min.js"></script>
<![endif]-->
<!--<script type="text/javascript" language="javascript" src="/assets/global/plugins/jquery.min.js"></script>-->
<script type="text/javascript" language="javascript" src="/assets/global/plugins/jquery.min.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/jquery-migrate.min.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/jquery-ui/jquery-ui.min.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/jquery.blockui.min.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/jquery.cokie.min.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/uniform/jquery.uniform.min.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/jqvmap/jqvmap/jquery.vmap.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.russia.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.world.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.europe.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.germany.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.usa.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/jqvmap/jqvmap/data/jquery.vmap.sampledata.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/flot/jquery.flot.min.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/flot/jquery.flot.resize.min.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/flot/jquery.flot.categories.min.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/jquery.pulsate.min.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/bootstrap-daterangepicker/moment.min.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/fullcalendar/fullcalendar.min.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/jquery-easypiechart/jquery.easypiechart.min.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/jquery.sparkline.min.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/bootbox/bootbox.min.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/bootstrap-toastr/toastr.min.js" type="text/javascript" ></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/jquery-notific8/jquery.notific8.min.js" type="text/javascript" ></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/jquery-validation/js/jquery.validate.js" type="text/javascript" ></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/jquery-validation/js/additional-methods.min.js" type="text/javascript" ></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/bootstrap-wizard/jquery.bootstrap.wizard.min.js" type="text/javascript" ></script>
<script type="text/javascript" language="javascript" src="/assets/global/plugins/select2/select2.min.js" type="text/javascript" ></script>

<!--<script type="text/javascript" src="/assets/global/scripts/datatable.js"></script>-->
<!--<script type="text/javascript" src="/assets/global/plugins/datatables/media/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>-->


<script type="text/javascript" language="javascript"  src="/assets/global/plugins/datatables/media/js/jquery.dataTables.js"></script>
<script type="text/javascript" src="/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>

<script type="text/javascript" language="javascript"  src="/assets/global/plugins/datatables/extensions/TableTools/js/dataTables.tableTools.js"></script>
<script type="text/javascript" src="/assets/global/plugins/datatables/extensions/ColReorder/js/dataTables.colReorder.min.js"></script>
<script type="text/javascript" src="/assets/global/plugins/datatables/extensions/Scroller/js/dataTables.scroller.min.js"></script>
<script type="text/javascript" src="/assets/global/scripts/jquery.dataTables.columnFilter.js"></script>

<script type="text/javascript" src="/assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
<script type="text/javascript" src="/assets/global/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js"></script>
<script type="text/javascript" src="/assets/global/plugins/clockface/js/clockface.js"></script>
<script type="text/javascript" src="/assets/global/plugins/bootstrap-daterangepicker/moment.min.js"></script>
<script type="text/javascript" src="/assets/global/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
<script type="text/javascript" src="/assets/global/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.js"></script>
<script type="text/javascript" src="/assets/global/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
<script type="text/javascript" src="/assets/global/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.es.min.js"></script>

<script src="/assets/global/plugins/jstree/dist/jstree.js"></script>

<script src="/assets/admin/pages/scripts/ui-tree.js"></script>
<script type="text/javascript" language="javascript" src="/assets/global/scripts/metronic.js"></script>
<script type="text/javascript" language="javascript" src="/assets/admin/layout/scripts/layout.js"></script>
<script type="text/javascript" language="javascript" src="/assets/admin/layout/scripts/quick-sidebar.js"></script>
<script type="text/javascript" language="javascript" src="/assets/admin/layout/scripts/miapp.js"></script>
<script type="text/javascript" language="javascript" src="/assets/admin/layout/scripts/app-custom.js"></script>
<script type="text/javascript" language="javascript" src="/assets/admin/pages/scripts/index.js"></script>
<script type="text/javascript" language="javascript" src="/assets/admin/pages/scripts/tasks.js"></script>
<script type="text/javascript" language="javascript" src="/assets/admin/pages/scripts/form-wizard.js"></script>
<!--<script type="text/javascript" language="javascript" src="/js/inactivo.js"></script>-->
<script>
    jQuery(document).ready(function() {
        Metronic.init(); // init metronic core components
        Layout.init(); // init current layout
        QuickSidebar.init(); // init quick sidebar
        MiApp.init(); // init demo features
        $('.page-sidebar .ajaxify.start').click() // load the content for the dashboard page.
        FormWizard.init();
        bootbox.setDefaults({
            locale: "es",
            title: "Confirmación"
        });
        AppCustom.init();
        //UITree.init();



        ///Index.init();
        //Index.initCharts(); // init index page's custom scripts
    });
</script>
<?php echo $this->inlineScript() ?>
</body>
</html>