<div class="modal-header  label-default">
 	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
	<div><i class="fa fa-windows"></i> Base de Datos - Nuevo Registro</div>
 </div>

<?php

$form = $this->form;
$form->setAttribute('action', $this->url('administracion/default', array('controller' => 'gestion', 'action' => 'nuevo')));
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>
<div class="modal-body">


          <?php echo $this->formInput($form->get('id_gp'));?>
            <div class="row">
                <label class="col-lg-3 control-label"><?php echo $this->formLabel($form->get('gestion')); ?></label>
                <div class="col-lg-9"><?php echo $this->formText($form->get('gestion'));?></div>
            </div>
            <div class="row">
                <label class="col-sm-3 control-label"><?php echo $this->formLabel($form->get('periodo')); ?></label>
                <div class="col-sm-9"><?php echo $this->formText($form->get('periodo'));?></div>
            </div>
            <div class="row">
                <label class="col-sm-3 control-label"><?php echo $this->formLabel($form->get('descripcion')); ?></label>
                <div class="col-sm-9"><?php echo $this->formElement($form->get('descripcion'));?></div>
            </div>

            <div class="row">
                <label class="col-sm-3 control-label"><?php echo $this->formLabel($form->get('estado')); ?></label>
                <div class="col-sm-9"><?php echo $this->formElement($form->get('estado'));?></div>
            </div>

            <div class="row">
                <label class="col-sm-3 control-label"><?php echo $this->formLabel($form->get('fecha_ini')); ?></label>
                <div class="col-sm-9">
                    <div class="input-group input-small date date-picker" data-date="<?php echo $form->getValue('fecha_ini')  ?>" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                        <?php echo $this->formText($form->get('fecha_ini'));?>
                        <span class="input-group-btn">
                                <button class="btn btn-sm blue" type="button">
                                    <i class="fa fa-calendar"></i>
                                </button>
                            </span>
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-3 control-label"><?php echo $this->formLabel($form->get('fecha_fin')); ?></label>
                <div class="col-sm-9">
                    <div class="input-group input-small date date-picker" data-date="<?php echo $form->getValue('fecha_fin')  ?>" data-date-format="dd-mm-yyyy">
                        <?php echo $this->formText($form->get('fecha_fin'));?>
                        <span class="input-group-btn">
                            <button class="btn btn-sm blue" type="button">
                                <i class="fa fa-calendar"></i>
                            </button>
                        </span>
                    </div>
                </div>
            </div>


            <div class="row">
                <label class="col-sm-3 control-label"><?php echo $this->formLabel($form->get('vigencia')); ?></label>
                <div class="col-sm-9"><?php echo $this->formElement($form->get('vigencia'));?></div>
            </div>



</div>
<div class="modal-footer label-default">
    <?php echo $this->formElement($form->get('Registrar'))?>
    <button type="button" class="btn default btn-xs" data-dismiss="modal"><?php echo  $this->id_gp=='0'?'Cancelar':'Cerrar'?></button>
</div>
<?php echo $this->form()->closeTag($form); ?>
<!-- END PAGE LEVEL STYLES -->
<script>

jQuery(document).ready(function() {
	handleFormBases();

    if (jQuery().datepicker) {
        $('.date-picker').datepicker({
            rtl: Metronic.isRTL(),
            orientation: "left",
            autoclose: true,
            language: 'es',
            //format: 'd-m-',
            //minDate: '01/01/2016',
            //maxDate: '12/31/2016',
        });
        //$('body').removeClass("modal-open"); // fix bug when inline picker is used in modal
    }
	
});

                    
function handleFormBases() {
    var form1 = $('#frmPeriodo');
    var error1 = $('.alert-danger', form1);
    var success1 = $('.alert-success', form1);

    
    form1.validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: false, // do not focus the last invalid input
        ignore: "",
        rules: {
            gestion: {
        		required:true,
            },
            periodo: {
        		required:true,
            },
            descripcion: {
            	required:true,
            },
            estado: {
        		required:true,
            },
            fecha_ini: {
            	required: true,
            },
            fecha_fin: {
        		required:true,
            },            
            vigencia: {
        		required:true,
            },
        },
        messages: { // custom messages for radio buttons and checkboxes
            gestion: {
                required: "Requerido!!",
           },
            periodo: {
                required: "Requerido!!",
           },
            descripcion: {
                required: "Requerido!!",
          },
            estado: {
                required: "Requerido!!",
           },
            fecha_ini: {
                required: "Requerido!!",
           },
            fecha_fin: {
                required: "Requerido!!",
           },
            vigencia: {
                required: "Requerido!!",
           },
        },

        invalidHandler: function (event, validator) { //display error alert on form submit              
            success1.hide();
            error1.show();
            Metronic.scrollTo(error1, -200);
        },

        highlight: function (element) { // hightlight error inputs
            $(element)
                .closest('.row').addClass('has-error'); // set error class to the control group
        },

        unhighlight: function (element) { // revert the change done by hightlight
            $(element)
                .closest('.row').removeClass('has-error'); // set error class to the control group
        },

        success: function (label) {
            label
                .closest('.row').removeClass('has-error'); // set success class to the control group
        },

        submitHandler: function (form) {
        	ajaxEnviar(form,'administracion/gestion/index','#result');
        }
    });

} 
    function ajaxEnviar (form,url,div) {

       var vsl_mensaje = "";

        var formData = new FormData(form);

       if ($('#id_gp').val() == '0'){
         vsl_mensaje = "ESTA SEGURO DE GUARDAR EL REGISTRO?";
       }else{
         vsl_mensaje = "ESTA SEGURO DE ACTUALIZAR EL REGISTRO?";
           }



        bootbox.setDefaults({
            locale: "es",
            //title: "Confirmación"
        });
        bootbox.confirm(vsl_mensaje, function(result) {
            if(result){

                $('#modal_nuevo').modal('hide');

                Metronic.startPageLoading();
                $.ajax({
                    type: $(form).attr('method'),
                    url: $(form).attr('action'),
                    cache: false,
                    contentType: false,
                    processData: false,
                    //data: $(form).serialize(),
                    data: formData,
                   // mimeType:"multipart/form-data",
                    dataType: "json",
                    success: function (data) {
                        if(data.respuesta){
                            //$('#modal_nuevo').show();
                            //jQuery(div).load(url);
                            //jQuery('.page-content .page-content-body').load(url);
                            //jQuery('#result').load(url);
                            actualizarTabla();

                            toastr.success(data.mensaje, 'SUCCESS');
                            Metronic.stopPageLoading();

                        }else{
                            //$('#modal_nuevo').modal().show();
                            toastr.error(data.mensaje, 'ERROR');
                            Metronic.stopPageLoading();
                        }
                    },
                    error : function(jqXHR, status, error) {
                        toastr.error('OCURRRIO UN ERROR AL EJECUTAR LA PAGINA', 'ERROR');
                        Metronic.stopPageLoading();
                    }
                });
            }
        });
    }
    

                    

</script>

