<a href="/">
    <!--<img src="/assets/admin/layout/img/logo.png" alt="logo" class="logo-default"/>-->
    <img src="/img/logo-mefp.jpg" height="40" alt="logo" class="logo-default"/>
    <span class="text-logo"><?php echo \MisLibrerias\DatosSesion::getAplicacion() ?></span>
</a>
<div class="menu-toggler sidebar-toggler hide">
    <!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
</div>