<div class="top-menu">
    <ul class="nav navbar-nav pull-right">

        <li class="dropdown" id="header_notification_bar">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                <i class="fa fa-clock-o"></i>
					<span class="badge badge-default" id="timeApp">
					</span>
            </a>
        </li>

        <?php //echo $this->partial('layout/partials/partial-top-navigation-menu-notification', array()); ?>
        <?php //echo $this->partial('layout/partials/partial-top-navigation-menu-inbox', array()); ?>
        <?php //echo $this->partial('layout/partials/partial-top-navigation-menu-todo', array()); ?>
        <?php echo $this->partial('layout/partials/partial-top-navigation-menu-user-login', array()); ?>
        <?php //echo $this->partial('layout/partials/partial-top-navigation-menu-quick-sidebar', array()); ?>

    </ul>
</div>