<h4>
    <?php echo sprintf('Su nueva contraseña ha sido modificada. <br>Un mensaje de correo electrónico con su nueva clave ha sido enviada a <b>%s</b>. <br><br>Por favor, compruebe su bandeja de entrada, gracias!', $usr_email);?>
</h4>

<div align="right" style="padding: 0 10px 10px 0;">
    <a href="<?php echo $this->url('auth-doctrine/default', array('controller' => 'index', 'action' => 'login'));?>">INICIO</a>
</div>