<p class="text-center text-danger" style="font-weight: bold;">
    <?php echo $this->messages; ?>
</p>
<div class="login-panel panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Olvido su Clave?</h3>
    </div>
    <div class="panel-body">
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('auth-doctrine/default', array('controller' => 'registration', 'action' => 'recordar-password')));
            $form->prepare();
            echo $this->form()->openTag($form);
        ?>
        <fieldset>

            <div
                class="form-group <?php if ($this->formElementErrors($form->get('usrEmail'))) echo "has-error"; else echo ""; ?>">
                <span class="col-md-12"><?php echo $this->formLabel($form->get('usrEmail')); ?></span>

                <div class="col-md-12">
                    <?php echo $this->formInput($form->get('usrEmail')); ?>
                    <?php if ($this->formElementErrors($form->get('usrEmail'))) ?>
                    <span>
                        <?php echo $this->formElementErrors($form->get('usrEmail')) ?>
                    </span>
                </div>
            </div>
            <div class="form-actions fluid">
                <div class="col-md-offset-3 col-md-9">
                    <?php echo $this->formRow($form->get('submit')); ?>
                    <a href="<?php echo $this->url('auth-doctrine/default', array('controller' => 'index', 'action' => 'logout')); ?>">
                        <button class="btn btn-warning" type="button">Cancelar</button>
                    </a>
                </div>
            </div>

        </fieldset>
        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>


<div align="right" style="padding: 0 10px 10px 0;">
    <a href="<?php echo $this->url('auth-doctrine/default', array('controller' => 'index', 'action' => 'login')); ?>">INICIO</a>
</div>