<h3 class="page-title">
   Control de Avance <small> </small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="/">Evaluacion</a>
            <i class="fa fa-angle-right"></i>
        </li>
           <li>
            <a href="eadmControlAvance1">Control de Avance</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Control de Avance</a>
        </li>
    </ul>
</div>

<div class="portlet box purple">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-pencil"></i> Control de Avance 
        </div>
        <div class="tools">
            <a href="" class="reload"></a>
        </div>
    </div>
    <div class="portlet-body form">
        <form role="form">
            <div class="form-body">
                <div class="form-group">
                                        
                                    <div class="form-group">
                                        <label class="col-md-2 control-label">Buscar por unidad:</label>
                                        <div class="col-md-3">
                                            
                                            <input type="text" class="form-control" placeholder=" ">
                                       
                                            
                                        </div>
                                        <label class="col-md-2 control-label">Buscar por item:</label>
                                        <div class="col-md-3">
                                            
                                            <input type="text" class="form-control" placeholder=" ">
                                       
                                            
                                        </div>

                                    </div>
                                    </br></br></br>
                   
                                    <div class="row">
                                        <div class="col-md-offset-5 col-md-8">
                                            <button type="button" class="btn purple">Buscar</button>
                                            <button type="button" class="btn purple">Ver Todos</button>

                                        </div>

                                    </br></br>
                                </div>
                                 <div class="col-md-offset-10 col-md-8">
                                Imprimir: <i class="fa fa-print"></i>
                            </div>
                                <div class="table-scrollable">
                                <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>
                                         #
                                    </th>
                                    <th>
                                         Unidad/Item
                                    </th>
                                    <th>
                                         Avance
                                    </th>
                                    <th>
                                         Plazo
                                    </th>

                                    <th>
                                        Aumentar Plazo
                                    </th>
                    
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>
                                         1
                                    </td>
                                    <td>
                                         Unidad de Recursos Humanos
                                    </td>
                                    <td>
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                                                <span class="sr-only">
                                                100% Complete </span>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                         01/10/2016
                                    </td>
                                    <td>

                                    <button class="btn popovers" data-container="body" data-trigger="hover" data-placement="right" data-content= "SI        NO" data-original-title="Desea ampliar el plazo para la evaluacion?">Aumentar Plazo</button>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                         2
                                    </td>
                                    <td>
                                         Unidad Financiera
                                    </td>
                                     <td>
                                       <div class="progress">
                                            <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                                <span class="sr-only">
                                              20% Complete </span>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                         10/10/2016
                                    </td>
                                   <td>
                                    
                            <button class="btn popovers" data-container="body" data-trigger="hover" data-placement="right" data-content="Popover body goes here! Popover body goes here!" data-original-title="Popover in right">Aumentar Plazo</button>
                                   </td>
                                </tr>
                                </tbody>
                                </table>
                            </div>
            </div>
        </form>
    </div>
</div>
