        <form role="form">
            <div class="form-body">
                <div class="row">
                    <div class="form-group">


                        <label class="col-md-2 control-label">Nro de Item:</label>

                        <div class="col-md-4">
                            <input type="text" class="form-control" placeholder=" ">
                        </div>
                        <label class="col-md-1 control-label">Unidad:</label>

                        <div class="col-md-4">
                            <input type="text" class="form-control" placeholder=" ">
                        </div>


                        </br></br>

                        <label class="col-md-2 control-label">Buscar:</label>

                        <div class="col-md-4">
                            <input type="text" class="form-control" placeholder=" ">
                        </div>

                        <div class="col-md-offset-1 col-md-3">
                            <button type="button" class="btn purple">Buscar</button>
                        </div>

                        </br><hr>

                    </div>

                </div>
            </div>
        </form>

        <div class="table-scrollable">
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>
                        #
                    </th>
                    <th>
                        Reportes
                    </th>
                    <th>
                        Ver reporte
                    </th>
                    <th>
                        Imprimir
                    </th>


                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        1
                    </td>
                    <td>
                        Reporte POAI
                    </td>
                    <td>
                        <button type="button" class="btn purple">Ver Reporte</button>
                    </td>
                    <td>
                        <i class="fa fa-print"></i>
                    </td>

                </tr>
                <tr>
                    <td>
                        2
                    </td>
                    <td>
                        Reporte de Seguimiento
                    </td>
                    <td>
                        <button type="button" class="btn purple">Ver Reporte</button>
                        <a href="/"
                           data-target="#modal_reporte"
                           data-toggle="modal"
                           class="btn btn-primary"> Ver Reporte</a>
                    </td>
                    <td>
                        <i class="fa fa-print"></i>
                    </td>

                </tr>
                </tbody>
            </table>
        </div>

        <div class="modal" id="modal_reporte" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                </div>
            </div>
        </div>