<h3 class="page-title">
   Reportes de POAI's <small> </small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="/">Evaluacion</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="eelabReportesPoais1">Reportes POAI's</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Reportes de POAI's</a>
        </li>
    </ul>
</div>

<div class="portlet box purple">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-pencil"></i> Reportes de POAI's
        </div>
        <div class="tools">
            <a href="" class="reload"></a>
        </div>
    </div>
    <div class="portlet-body form">
        <form role="form">
            <div class="form-body">
                <div class="row">                 
                    <div class="form-group">
                    <label class="col-md-2 control-label">Nro de Item: </label>
                        <div class="col-md-3">
                            <input type="text" class="form-control" placeholder=" ">
                             </br>
                        </div>
                    </br></br></br>
                        <label class="col-md-2 control-label">Buscar: </label>
                        <div class="col-md-3">
                            <input type="text" class="form-control" placeholder=" ">
                             </br>
                        </div>
                    <div class="row">
                        <div class="col-md-offset-1 col-md-1">
                            <button type="button" class="btn purple">Buscar</button> 
                        </div>
                    </div>
                </div>
                </div>
                <div class="portlet-body">
                            <div class="table-scrollable">
                                <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>
                                         Reportes
                                    </th>
                                    <th>
                                         Ver reportes
                                    </th>
                                    <th>
                                         Imprimir
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>
                                         Reporte POAI
                                    </td>
                                    <td>
                                         Ver Reporte <i class="fa fa-search"></i>
                                    </td>
                                    <td>
                                          Imprimir <i class="fa fa-print"></i>
                                    </td>
                                </tr>
                                 <tr>
                                    <td>
                                         Reporte del seguimiento
                                    </td>
                                    <td>
                                        Ver Reporte <i class="fa fa-search"></i>
                                    </td>
                                    <td>
                                          Imprimir <i class="fa fa-print"></i>
                                    </td>
                                </tr>
                                

                                </tbody>
                                </table>
                            </div>
                        </div>
            </div>
        </form>
    </div>
</div