<h3 class="page-title">
   Control de Avance <small> </small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="/">Evaluacion</a>
            <i class="fa fa-angle-right"></i>
        </li>
           <li>
            <a href="#">Control de Avance</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Control de Avance</a>
        </li>
    </ul>
</div>

<div class="portlet box purple">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-pencil"></i> Control de Avance 
        </div>
        <div class="tools">
            <a href="" class="reload"></a>
        </div>
    </div>
    <div class="portlet-body form">
        <form role="form">
            <div class="form-body">
                <div class="row">                 
                    <div class="form-group">
                        <label class="col-md-2 control-label">Buscar por item:</label>
                            <div class="col-md-3">
                                <input type="text" class="form-control" placeholder=" ">
                            </div>
                        <div class="col-md-offset-5 col-md-8">
                            <button type="button" class="btn purple">Buscar</button>
                            <button type="button" class="btn purple">Ver Todos</button>
                        </br></br>
                        </div>
                        <div class="table-scrollable">
                                <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>
                                         Item
                                    </th>
                                    <th>
                                         Ver
                                    </th>
                                    <th>
                                         Estado
                                    </th>
                                    <th>
                                         Control de Evaluacion
                                    </th>

                                    <th>
                                        Imprimir
                                    </th>
                    
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>
                                         301
                                    </td>
                                    <td>
                                         Ver <i class="fa fa-search"></i>
                                    </td>
                                    <td>
                                          <span class="label label-sm label-success">
                                        Finalizado</span>
                                    </td>
                                    <td>
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                                                <span class="sr-only">
                                              100% Complete </span>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                    Imprimir <i class="fa fa-print"></i>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                         302
                                    </td>
                                    <td>
                                         Ver <i class="fa fa-search"></i>
                                    </td>
                                    <td>
                                          <span class="label label-sm label-danger">
                                        Por llenar </span>
                                    </td>
                                    <td>
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
                                                <span class="sr-only">
                                              0% Complete </span>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                    Imprimir <i class="fa fa-print"></i>
                                    </td>
                                </tr>
                                </tbody>
                                </table>
                            </div>
                    </div>    
                </div>
            </div>
        </form>
    </div>
</div>
