<h3 class="page-title">
    Control de Avance <small> </small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="/">Formulacion</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="fadmGestionPoais">Gestion de POAI's</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Control de Avance</a>
        </li>
    </ul>
</div>
<!-- END PAGE HEADER-->

<div class="portlet box red">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i> Control de Avance
        </div>
        <div class="tools">
            <a href="" class="reload"></a>
        </div>
    </div>
  
    <div class="portlet-body">
                            <div class="table-toolbar">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="btn-group">
                                            
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="btn-group pull-right">
                                            <button class="btn dropdown-toggle" data-toggle="dropdown">Opciones <i class="fa fa-angle-down"></i>
                                            </button>
                                            <ul class="dropdown-menu pull-right">
                                                <li>
                                                    <a href="javascript:;">
                                                    Imprimir </a>
                                                </li>
                                                <li>
                                                    <a href="javascript:;">
                                                    Guardar como PDF </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                        <label class="col-md-3 control-label">Unidad</label>
                                        <div class="col-md-5">
                                            <select class="form-control">
                                                <option>Unidad de Tecnologias de Informacion</option>
                                                <option>Unidad de Recursos Humanos</option>
                                                <option>Unidad Financiera</option>
                                            </select>
                                        </div>
                                    </div>
                                    </br></br>
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Buscar por Item:</label>
                                        <div class="col-md-3">
                                            
                                            <input type="text" class="form-control" placeholder=" ">
                                            <span class="help-block">
                                            Ejemplo: 343 </span>
                                            </br>
                                        </div>
                                    </div>
                                     <div class="form-actions ">
                                    <div class="row">
                                        <div class="col-md-offset-5 col-md-8">
                                            <button type="button" class="btn red">Buscar</button>
                                            <button type="button" class="btn red">Ver todos</button> 
                                        </br></br>
                                        </div>

                                    </div>
                                </div>

                            <table class="table table-striped table-hover table-bordered" id="sample_editable_1">
                            <thead>
                            <tr>
                                <th>
                                     #
                                </th>
                                <th>
                                     Unidad Organizacional
                                </th>
                                <th>
                                     Avance
                                </th>
                                <th colspan="2" class="text-center">
                                     Plazo
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>
                                     1
                                </td>
                                <td>
                                     UTI    
                                </td>
                                <td>
                                     loading...
                                </td>
                                <td >
                                     01/03/2016
                                </td>
                                <td>
                                    01/10/2016
                                </td>
                            </tr>
                            <tr>
                                <td>
                                     2
                                </td>
                                <td>
                                     RRHH    
                                </td>
                                <td>
                                     loading...
                                </td>
                                <td >
                                     01/04/2016
                                </td>
                                <td>
                                    01/11/2016
                                </td>
                            </tr>
                            <tr>
                                <td>
                                     3
                                </td>
                                <td>
                                     FINANCIERA    
                                </td>
                                <td>
                                     loading...
                                </td>
                                <td >
                                     01/03/2016
                                </td>
                                <td>
                                    01/11/2016
                                </td>
                            </tr>
                            </tbody>
                            </table>
                        </div>


</div>


<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="/assets/global/plugins/respond.min.js"></script>
<script src="/assets/global/plugins/excanvas.min.js"></script> 
<![endif]-->
<script src="/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
<!-- IMPORTANT! Load jquery-ui.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<script src="/assets/global/plugins/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="/assets/global/plugins/select2/select2.min.js"></script>
<script type="text/javascript" src="/assets/global/plugins/datatables/media/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="/assets/global/scripts/metronic.js" type="text/javascript"></script>
<script src="/assets/admin/layout/scripts/layout.js" type="text/javascript"></script>
<script src="/assets/admin/layout/scripts/quick-sidebar.js" type="text/javascript"></script>
<script src="/assets/admin/layout/scripts/demo.js" type="text/javascript"></script>
<script src="/assets/admin/pages/scripts/table-editable.js"></script>

<script>
jQuery(document).ready(function() {       
    //Metronic.init(); // init metronic core components
    //Layout.init(); // init current layout
    //QuickSidebar.init(); // init quick sidebar
    //Demo.init(); // init demo features
   // TableEditable.init();
});
</script>