<h3 class="page-title">
    Aprobacion POAI´s <small> </small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="/">Formulacion</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="fadmGestionPoais">Gestion de POAI's</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Aprobacion POAI´s</a>
        </li>
    </ul>
</div>
<!-- END PAGE HEADER-->
<div class="portlet box red">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i> Aprobacion de POAI's
        </div>
        <div class="tools">
            <a href="" class="reload"></a>
        </div>
    </div>
    <div class="portlet-body form">
        <form role="form">
            <div class="form-body">
                                    
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Unidad</label>
                                        <div class="col-md-7">
                                            <select class="form-control">
                                                <option>Unidad de Tecnologias de Informacion</option>
                                                <option>Unidad de Recursos Humanos</option>
                                                <option>Unidad Financiera</option>
                                            </select>
                                        </br> 
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Item: </label>
                                        <div class="col-md-9">
                                            <input type="text" class="form-control input-inline input-medium" placeholder="Ingresar nro de Item">
                                            <span class="help-inline">
                                             </span>
                                            </br> </br>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Gestion:</label>
                                        <div class="col-md-9">
                                            <input type="text" class="form-control input-inline input-medium" placeholder="Ingresar gestion">
                                            <span class="help-inline">
                                             </span>
                                            </br> </br>
                                        </div>
                                    </div>

                                    </br></br></br>
                                 
                                    <div class="row">
                                        <div class="col-md-offset-5 col-md-8">
                                            <button type="button" class="btn red">Buscar</button>
                                            <button type="button" class="btn red">Ver todos</button> 
                                        </br></br>
                                    </div>
                                </div>

                            <table class="table table-striped table-hover table-bordered" id="sample_editable_1">
                            <thead>
                            <tr>
                                <th>
                                     #
                                </th>
                                <th>
                                     Item
                                </th>
                                <th>
                                     POAI
                                </th>
                                <th >
                                     Estado
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>
                                     1
                                </td>
                                <td>
                                     001    
                                </td>
                                <td>
                                     Ver POAI
                                </td>
                                <td >
                                     Aprobado
                                </td>
                             
                            </tr>
                            <tr>
                                <td>
                                     2
                                </td>
                                <td>
                                     002   
                                </td>
                                <td>
                                     Ver POAI
                                </td>
                                <td >
                                     Aprobar POAI
                                </td>
                       >
                            </tr>
                            <tr>
                                <td>
                                     3
                                </td>
                                <td>
                                    003    
                                </td>
                                <td>
                                     Ver POAI
                                </td>
                                <td >
                                     Aprobar POAI
                                </td>
                            </tr>
                            </tbody>
                            </table>
            </div>
        </form>
    </div>
</div>

