<h3 class="page-title">
    Registro de POAI´s <small> </small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="/">Formulacion</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="felabRevisionPoais">Revision de POAI's</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Registro de POAI´s</a>
        </li>
    </ul>
</div>
<!-- END PAGE HEADER-->
<div class="portlet box red">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i> Registro y Revision de POAI's
        </div>
        <div class="tools">
            <a href="" class="reload"></a>
        </div>
    </div>
    <div class="portlet-body form">
        <form role="form">
            <div class="form-body">
                 <div class="form-group">
                                        <label class="col-md-3 control-label">Unidad:</label>
                                        <div class="col-md-6">
                                            
                                            <input type="text" class="form-control" placeholder="UNIDAD DE RECURSOS HUMANOS">
                                            <span class="help-block">
                                            </span>
                                            </br>
                                        </div>
                                    </div>
                <table class="table table-striped table-hover table-bordered" id="sample_editable_1">
                            <thead>
                            <tr>
                                <th>
                                     Nro
                                </th>
                                <th>
                                     Item
                                </th>
                                <th>
                                     POAI
                                </th>
                                <th >
                                    Estado
                                </th>
                                <th>
                                    Observacion
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>
                                     1
                                </td>
                                <td>
                                     203    
                                </td>
                                <td>
                                     Revisar Poai
                                </td>
                                <td >
                                     Revisado
                                </td>
                                <td>
                                    qwerty
                                </td>   
                             </tr>
                            <tr>
                                <td>
                                     2
                                </td>
                                <td>
                                     243    
                                </td>
                                <td>
                                     Revisar Poai
                                </td>
                                <td >
                                     Pendiente
                                </td>
                                <td>
                                    asdfgh
                                </td>                        
                            </tr>
                            <tr>
                                <td>
                                     3
                                </td>
                                <td>
                                     253    
                                </td>
                                <td>
                                     Revisar Poai
                                </td>
                                <td >
                                     Pendiente
                                </td>
                                <td>
                                    qwerty
                                </td>
                              
                            </tr>
                            </tbody>
                            </table>
            </div>
        </form>
    </div>
</div>

