<head>
    
</head> 
<h3 class="page-title">
    POAI <small> </small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="/">Formulacion</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Comenzar POAI</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Nro de Item</a>
        </li>
    </ul>
</div>
<div class="portlet box red">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i> Planificacion Operativa Anual Individual
        </div>
        <div class="tools">
            <a href="" class="reload"></a>
        </div>
    </div>
      <div class="portlet-body form">
        <div class="tabbable tabbable-tabdrop">
            <ul class="nav nav-tabs">
                <li class="active">
                    <a href="#tab1" data-toggle="tab">I. Identificación</a>
                </li>
                <li>
                    <a href="#tab2" data-toggle="tab">II. Descripción</a>
                </li>
                <li>
                    <a href="#tab3" data-toggle="tab">III. Especificación</a>
                </li>
                <li>
                    <a href="#tab4" data-toggle="tab">Confirmacion</a>
                </li>
                <li>
                    <a href="#tab5" data-toggle="tab">IV. Resultados Esperados</a>
                </li>
                <li>
                    <a href="#tab6" data-toggle="tab">V. Compromiso</a>
                </li>
       

            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="tab1">

                    <div class="col-md-10" >
                        <h3 > <b> 1.1. Datos del Puesto </b> </h3>
                    </div>

                    <form class="form-horizontal" role="form">

                        <div class="form-group">
                            <label for="text" class="col-md-4 control-label">Nro de Item: </label>
                            <div class="col-md-8">
                                </br><label for = "denominacion_cargo" id="lab_denominacion_cargo"> 301 </label>
                            </div>

                            <label for="text" class="col-md-4 control-label">Nivel: </label>
                            <div class="col-md-8">
                                </br><label for = "denominacion_cargo" id="lab_denominacion_cargo"> 5 </label>
                            </div>

                            <label for="text" class="col-md-4 control-label">Categoría: </label>
                            <div class="col-md-8">
                                </br><label for = "denominacion_cargo" id="lab_denominacion_cargo"> OPERATIVO </label>
                            </div>

                            <label for="text" class="col-md-4 control-label">Denominación del cargo: </label>
                            <div class="col-md-8">
                                </br><label for = "denominacion_cargo" id="lab_denominacion_cargo"> PROFESIONAL II </label>
                            </div>
                    
                            <label for="text" class="col-md-4 control-label">Denominacion del puesto: </label>
                            <div class="col-md-8">
                                </br><label for = "denominacion_puesto" id="lab_denominacion_puesto"> RESPONSABLE DE MOVILIDAD Y REGISTRO DE PERSONAL </label>
                            </div>

                            <label for="text" class="col-md-4 control-label">Dependencia: </label>
                            <div class="col-md-8">
                                </br><label for = "dependencia" id="lab_dependencia"> UNIDAD DE RECURSOS HUMANOS</label>
                            </div>
                        </div>
                    </form>

                    <hr>

                    <div class="col-md-15" >
                        <h3> &nbsp <b> 1.2. Relaciones del Puesto </b> </h3>
                    </div> 
                    <div class="col-md-15" >
                        <h4> &nbsp &nbsp <b>1.2.1. Relaciones Jerárquicas </b></h4></br>
                    </div>


                    <div class="form-group">

                        <div class="col-md-5">
                            <div class="form-group form-md-line-input form-md-floating-label has-error">
                                <input type="text" class="form-control" id="form_control_1">
                                <label for="form_control_1">Depende de: </label>
                            </div>
                        </div>

                        <div class="col-md-5">
                            <div class="form-group form-md-line-input form-md-floating-label has-error">
                                <input type="text" class="form-control" id="form_control_1">
                                <label for="form_control_1">Supervisa a: </label>
                            </div>
                            <div class="form-group form-md-line-input form-md-floating-label has-error">
                                <input type="text" class="form-control" id="form_control_1">
                                <label for="form_control_1">Supervisa a: </label>
                            </div>
                            <div class="form-group form-md-line-input form-md-floating-label has-error">
                                <input type="text" class="form-control" id="form_control_1">
                                <label for="form_control_1">Supervisa a: </label>
                            </div>
                          
                        </div>
                        <div class="col-md-1">
                            <div class="form-group form-md-line-input form-md-floating-label has-error">
                                <input type="text" class="form-control" id="form_control_1">
                                <label for="form_control_1">Cantidad: </label>
                            </div>
                            <div class="form-group form-md-line-input form-md-floating-label has-error">
                                <input type="text" class="form-control" id="form_control_1">
                                <label for="form_control_1">Cantidad: </label>
                            </div>
                            <div class="form-group form-md-line-input form-md-floating-label has-error">
                                <input type="text" class="form-control" id="form_control_1">
                                <label for="form_control_1">Cantidad: </label>
                            </div>
                        </br></br></br>
                        </div>
                    </div>
                   
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> 1.2.2. Relaciones Intrainstitucionales </b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b>  1.2.3. Relaciones Interinstitucionales </b> </h4>
                                </div>
                            </div>
                        </div>
                    </div> 

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">1. </label>
                                    </div>            
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">2. </label>
                                    </div>
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">3. </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">1. </label>
                                    </div>
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">2. </label>
                                    </div>
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">3. </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div> 

                </div>
            
    
                <div class="tab-pane " id="tab2">

                    <div class="col-md-10" >
                        <h3 > <b> 2.1. Objetivo del Puesto </b> </h3>
                    </div>
                    <form class="col-md-14">
                        <div class="form-group">
                            <div class="col-md-11">
                               <div class="form-group form-md-line-input form-md-floating-label has-error">
                                    <textarea class="form-control" rows="1"></textarea>
                                    <label for="form_control_1">Que hace?</label>
                                </div>
                           </div>
                        </div>
                        <div class="form-group">
                           <div class="col-md-11">
                               <div class="form-group form-md-line-input form-md-floating-label has-error">
                                    <textarea class="form-control" rows="1"></textarea>
                                    <label for="form_control_1">De que forma?</label>
                                </div>
                           </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-11">
                               <div class="form-group form-md-line-input form-md-floating-label has-error">
                                    <textarea class="form-control" rows="1"></textarea>
                                    <label for="form_control_1">Con que finalidad?</label>
                                </div>
                           </div>
                        </div>
                    </form>

                    <div class="col-md-10" >
                        <h3 > <b> 2.2. Normas a Cumplir </b> </h3>
                    </div >
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Normas Generales </b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b>  Normas Especificas</b> </h4>
                                </div>
                            </div>
                        </div>
                    </div>
                   
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option value="1">Option 1</option>
                                            <option value="2">Option 2</option>
                                            <option value="3">Option 3</option>
                                            <option value="4">Option 4</option>
                                        </select>
                                        <label for="form_control_1">Norma General</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--/span-->
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option value="1">Option 1</option>
                                            <option value="2">Option 2</option>
                                            <option value="3">Option 3</option>
                                            <option value="4">Option 4</option>
                                        </select>
                                        <label for="form_control_1">Norma Especifica</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                  
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option value="1">Option 1</option>
                                            <option value="2">Option 2</option>
                                            <option value="3">Option 3</option>
                                            <option value="4">Option 4</option>
                                        </select>
                                        <label for="form_control_1">Norma General</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--/span-->
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option value="1">Option 1</option>
                                            <option value="2">Option 2</option>
                                            <option value="3">Option 3</option>
                                            <option value="4">Option 4</option>
                                        </select>
                                        <label for="form_control_1">Norma Especifica</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option value="1">Option 1</option>
                                            <option value="2">Option 2</option>
                                            <option value="3">Option 3</option>
                                            <option value="4">Option 4</option>
                                        </select>
                                        <label for="form_control_1">Norma General</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--/span-->
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option value="1">Option 1</option>
                                            <option value="2">Option 2</option>
                                            <option value="3">Option 3</option>
                                            <option value="4">Option 4</option>
                                        </select>
                                        <label for="form_control_1">Norma Especifica</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option value="1">Option 1</option>
                                            <option value="2">Option 2</option>
                                            <option value="3">Option 3</option>
                                            <option value="4">Option 4</option>
                                        </select>
                                        <label for="form_control_1">Norma General</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--/span-->
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option value="1">Option 1</option>
                                            <option value="2">Option 2</option>
                                            <option value="3">Option 3</option>
                                            <option value="4">Option 4</option>
                                        </select>
                                        <label for="form_control_1">Norma Especifica</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option value="1">Option 1</option>
                                            <option value="2">Option 2</option>
                                            <option value="3">Option 3</option>
                                            <option value="4">Option 4</option>
                                        </select>
                                        <label for="form_control_1">Norma General</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--/span-->
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option value="1">Option 1</option>
                                            <option value="2">Option 2</option>
                                            <option value="3">Option 3</option>
                                            <option value="4">Option 4</option>
                                        </select>
                                        <label for="form_control_1">Norma Especifica</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-10" >
                        <h3 > <b> 2.3. Funciones del Puesto </b> </h3>
                    </div>
                    <div class="col-md-10" >
                            <h4 > <b>  Funciones Generales del Puesto </b> </h4>           
                    </div>
                    <form action="#" class="horizontal-form">  
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">1. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">2. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">3. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">4. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">5. </label>
                                                </div>
                                            </div>
                                        </div>                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">6. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">7. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">8. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">9. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">10. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                </form>         
                                <div class="col-md-10" >
                                    <h4 > <b>  Funciones Especificas del Puesto </b> </h4>
                                </div>
                                <form action="#" class="horizontal-form">  
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">1. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">2. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">3. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">4. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">5. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">6. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">7. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                               <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">8. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">9. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">10. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>

                                </form>
                </div>
     
                <div class="tab-pane " id="tab3">

                     <div class="col-md-10" >
                        <h3 > <b> 3.1. Formación </b> </h3>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Area de Formación </b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b>  Grado de Formación <br> Mínima Aceptable</b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Prioridad</b> </h4>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-11" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Area de Formación </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-15" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Estudiante de Secundaria y/o Primaria</option>
                                            <option>Bachiller</option>
                                            <option>Técnico Medio y/0 Estudiante Universitario (3er Año Vencido)</option>
                                            <option>Técnico Superior Univesitario con Conclusion de Plan de Estudios</option>
                                            <option>Licenciatura</option>
                                            <option>Diplomado</option>
                                            <option>Especialización</option>
                                            <option>Maestría</option>
                                        </select>
                                        <label for="form_control_1">Norma General</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="&nbsp;Escencial&nbsp;" data-off-text="&nbsp;Complementario&nbsp;" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-11" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Area de Formación </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-15" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Estudiante de Secundaria y/o Primaria</option>
                                            <option>Bachiller</option>
                                            <option>Técnico Medio y/0 Estudiante Universitario (3er Año Vencido)</option>
                                            <option>Técnico Superior Univesitario con Conclusion de Plan de Estudios</option>
                                            <option>Licenciatura</option>
                                            <option>Diplomado</option>
                                            <option>Especialización</option>
                                            <option>Maestría</option>
                                        </select>
                                        <label for="form_control_1">Norma General</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="&nbsp;Escencial&nbsp;" data-off-text="&nbsp;Complementario&nbsp;" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-11" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Area de Formación </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-15" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Estudiante de Secundaria y/o Primaria</option>
                                            <option>Bachiller</option>
                                            <option>Técnico Medio y/0 Estudiante Universitario (3er Año Vencido)</option>
                                            <option>Técnico Superior Univesitario con Conclusion de Plan de Estudios</option>
                                            <option>Licenciatura</option>
                                            <option>Diplomado</option>
                                            <option>Especialización</option>
                                            <option>Maestría</option>
                                        </select>
                                        <label for="form_control_1">Norma General</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="&nbsp;Escencial&nbsp;" data-off-text="&nbsp;Complementario&nbsp;" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-11" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Area de Formación </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-15" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Estudiante de Secundaria y/o Primaria</option>
                                            <option>Bachiller</option>
                                            <option>Técnico Medio y/0 Estudiante Universitario (3er Año Vencido)</option>
                                            <option>Técnico Superior Univesitario con Conclusion de Plan de Estudios</option>
                                            <option>Licenciatura</option>
                                            <option>Diplomado</option>
                                            <option>Especialización</option>
                                            <option>Maestría</option>
                                        </select>
                                        <label for="form_control_1">Norma General</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="&nbsp;Escencial&nbsp;" data-off-text="&nbsp;Complementario&nbsp;" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-11" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Area de Formación </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-15" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Estudiante de Secundaria y/o Primaria</option>
                                            <option>Bachiller</option>
                                            <option>Técnico Medio y/0 Estudiante Universitario (3er Año Vencido)</option>
                                            <option>Técnico Superior Univesitario con Conclusion de Plan de Estudios</option>
                                            <option>Licenciatura</option>
                                            <option>Diplomado</option>
                                            <option>Especialización</option>
                                            <option>Maestría</option>
                                        </select>
                                        <label for="form_control_1">Norma General</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="&nbsp;Escencial&nbsp;" data-off-text="&nbsp;Complementario&nbsp;" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>

                    <div class="col-md-10" >
                        <h3 > <b> 3.2. Experiencia </b> </h3>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Area de Experiencia </b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Experiencia </b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Sector <br> (y/o)</b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Prioridad</b> </h4>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Area de Experiencia </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                               <div class="form-group form-md-line-input form-md-floating-label has-error">
                                    <select class="form-control" id="form_control_1">
                                        <option value=""></option>
                                        <option>Laboral</option>
                                        <option>Profesional</option>
                                        <option>General</option>
                                        <option>Especifico</option>
                                    </select>
                                    <label for="form_control_1">Experiencia</label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="form-group form-md-line-input">
                                    <div class="col-md-10">
                                        <div class="md-checkbox">
                                            <div class="md-checkbox has-success">
                                                <input type="checkbox" id="checkbox1" class="md-check">
                                                <label for="checkbox1">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Publica</label>
                                            </div>
                                            <div class="md-checkbox has-warning">
                                                <input type="checkbox" id="checkbox2" class="md-check" >
                                                <label for="checkbox2">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Privada</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="Escencial" data-off-text="Complementario" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Area de Experiencia </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                               <div class="form-group form-md-line-input form-md-floating-label has-error">
                                    <select class="form-control" id="form_control_1">
                                        <option value=""></option>
                                        <option>Laboral</option>
                                        <option>Profesional</option>
                                        <option>General</option>
                                        <option>Especifico</option>
                                    </select>
                                    <label for="form_control_1">Experiencia</label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="form-group form-md-line-input">
                                    <div class="col-md-10">
                                        <div class="md-checkbox">
                                            <div class="md-checkbox has-success">
                                                <input type="checkbox" id="checkbox3" class="md-check">
                                                <label for="checkbox3">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Publica</label>
                                            </div>
                                            <div class="md-checkbox has-warning">
                                                <input type="checkbox" id="checkbox4" class="md-check" >
                                                <label for="checkbox4">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Privada</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="Escencial" data-off-text="Complementario" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Area de Experiencia </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                               <div class="form-group form-md-line-input form-md-floating-label has-error">
                                    <select class="form-control" id="form_control_1">
                                        <option value=""></option>
                                        <option>Laboral</option>
                                        <option>Profesional</option>
                                        <option>General</option>
                                        <option>Especifico</option>
                                    </select>
                                    <label for="form_control_1">Experiencia</label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="form-group form-md-line-input">
                                    <div class="col-md-10">
                                        <div class="md-checkbox">
                                            <div class="md-checkbox has-success">
                                                <input type="checkbox" id="checkbox5" class="md-check">
                                                <label for="checkbox5">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Publica</label>
                                            </div>
                                            <div class="md-checkbox has-warning">
                                                <input type="checkbox" id="checkbox6" class="md-check" >
                                                <label for="checkbox6">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Privada</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="Escencial" data-off-text="Complementario" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Area de Experiencia </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                               <div class="form-group form-md-line-input form-md-floating-label has-error">
                                    <select class="form-control" id="form_control_1">
                                        <option value=""></option>
                                        <option>Laboral</option>
                                        <option>Profesional</option>
                                        <option>General</option>
                                        <option>Especifico</option>
                                    </select>
                                    <label for="form_control_1">Experiencia</label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="form-group form-md-line-input">
                                    <div class="col-md-10">
                                        <div class="md-checkbox">
                                            <div class="md-checkbox has-success">
                                                <input type="checkbox" id="checkbox7" class="md-check">
                                                <label for="checkbox7">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Publica</label>
                                            </div>
                                            <div class="md-checkbox has-warning">
                                                <input type="checkbox" id="checkbox8" class="md-check" >
                                                <label for="checkbox8">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Privada</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="Escencial" data-off-text="Complementario" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Area de Experiencia </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                               <div class="form-group form-md-line-input form-md-floating-label has-error">
                                    <select class="form-control" id="form_control_1">
                                        <option value=""></option>
                                        <option>Laboral</option>
                                        <option>Profesional</option>
                                        <option>General</option>
                                        <option>Especifico</option>
                                    </select>
                                    <label for="form_control_1">Experiencia</label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="form-group form-md-line-input">
                                    <div class="col-md-10">
                                        <div class="md-checkbox">
                                            <div class="md-checkbox has-success">
                                                <input type="checkbox" id="checkbox9" class="md-check">
                                                <label for="checkbox9">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Publica</label>
                                            </div>
                                            <div class="md-checkbox has-warning">
                                                <input type="checkbox" id="checkbox10" class="md-check" >
                                                <label for="checkbox10">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Privada</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="Escencial" data-off-text="Complementario" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="col-md-10" >
                        <h3 > <b> 3.3. Registro Profesional </b> </h3>
                    </div>
                    <div class="col-md-11">
                        <div class="form-group form-md-line-input form-md-floating-label has-error">
                            <textarea class="form-control" rows="1"></textarea>
                            <label for="form_control_1">Escriba si es necesario cuando el puesto así lo requiera para el ejercicio de una profesión.</label>
                        </div>
                    </div>
                    <div class="col-md-10" >
                        <h3 > <b> 3.4. Competencias </b> </h3>
                    </div>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Competencias</b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-7">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Descripción</b> </h4>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Liderazgo</option>
                                            <option>Planificacion y Organizacion </option>
                                            <option>Habilidad de control</option>
                                            <option>Delegacion</option>
                                            <option>Desarrollo de los subordinados, equipo u otras personas</option>
                                            <option>Capacidad Critica</option>
                                            <option>Capacidad de decision</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Experiencia</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-7">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Descripcion </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Liderazgo</option>
                                            <option>Planificacion y Organizacion </option>
                                            <option>Habilidad de control</option>
                                            <option>Delegacion</option>
                                            <option>Desarrollo de los subordinados, equipo u otras personas</option>
                                            <option>Capacidad Critica</option>
                                            <option>Capacidad de decision</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Experiencia</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-7">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Descripcion </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Liderazgo</option>
                                            <option>Planificacion y Organizacion </option>
                                            <option>Habilidad de control</option>
                                            <option>Delegacion</option>
                                            <option>Desarrollo de los subordinados, equipo u otras personas</option>
                                            <option>Capacidad Critica</option>
                                            <option>Capacidad de decision</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Experiencia</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-7">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Descripcion </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Liderazgo</option>
                                            <option>Planificacion y Organizacion </option>
                                            <option>Habilidad de control</option>
                                            <option>Delegacion</option>
                                            <option>Desarrollo de los subordinados, equipo u otras personas</option>
                                            <option>Capacidad Critica</option>
                                            <option>Capacidad de decision</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Experiencia</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-7">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Descripcion </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Liderazgo</option>
                                            <option>Planificacion y Organizacion </option>
                                            <option>Habilidad de control</option>
                                            <option>Delegacion</option>
                                            <option>Desarrollo de los subordinados, equipo u otras personas</option>
                                            <option>Capacidad Critica</option>
                                            <option>Capacidad de decision</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Experiencia</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-7">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Descripcion </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-10" >
                        <h3 > <b> 3.5. Conocimientos Requeridos </b> </h3>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Descripción</b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <h4 > <b> Nivel</b> </h4>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <h4 > <b> Prioridad</b> </h4>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-12">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Descripcion </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="form-group form-md-line-input">
                                    <div class="col-md-10">
                                        <div class="md-radio-inline">
                                            <div class="md-radio has-error">
                                                <input type="radio" id="radio1" name="radio2" class="md-radiobtn">
                                                <label for="radio1">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Basico</label>
                                            </div>
                                            <div class="md-radio has-success">
                                                <input type="radio" id="radio2" name="radio2" class="md-radiobtn" >
                                                <label for="radio2">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Intermedio</label>
                                            </div>
                                            <div class="md-radio has-warning">
                                                <input type="radio" id="radio3" name="radio2" class="md-radiobtn">
                                                <label for="radio3">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Avanzado</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="Escencial" data-off-text="Complementario" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-12">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Descripcion </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="form-group form-md-line-input">
                                    <div class="col-md-10">
                                        <div class="md-radio-inline">
                                            <div class="md-radio has-error">
                                                <input type="radio" id="radio1" name="radio2" class="md-radiobtn">
                                                <label for="radio1">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Basico</label>
                                            </div>
                                            <div class="md-radio has-success">
                                                <input type="radio" id="radio2" name="radio2" class="md-radiobtn" >
                                                <label for="radio2">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Intermedio</label>
                                            </div>
                                            <div class="md-radio has-warning">
                                                <input type="radio" id="radio3" name="radio2" class="md-radiobtn">
                                                <label for="radio3">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Avanzado</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="Escencial" data-off-text="Complementario" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-12">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Descripcion </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="form-group form-md-line-input">
                                    <div class="col-md-10">
                                        <div class="md-radio-inline">
                                            <div class="md-radio has-error">
                                                <input type="radio" id="radio1" name="radio2" class="md-radiobtn">
                                                <label for="radio1">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Basico</label>
                                            </div>
                                            <div class="md-radio has-success">
                                                <input type="radio" id="radio2" name="radio2" class="md-radiobtn" >
                                                <label for="radio2">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Intermedio</label>
                                            </div>
                                            <div class="md-radio has-warning">
                                                <input type="radio" id="radio3" name="radio2" class="md-radiobtn">
                                                <label for="radio3">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Avanzado</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="Escencial" data-off-text="Complementario" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>

                    <div class="col-md-10" >
                        <h3 > <b> 3.6. Requisitos Constitucionales</b> </h3>
                    </div>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Descripción</b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Prioridad</b> </h4>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Contar con nacionalidad boliviana</option>
                                            <option>Ser mayor de edad </option>
                                            <option>Haber cumplido con los deberes militares</option>
                                            <option>No tener cargo de pliego ejecutoriado</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Experiencia</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="Escencial" data-off-text="Complementario" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Contar con nacionalidad boliviana</option>
                                            <option>Ser mayor de edad </option>
                                            <option>Haber cumplido con los deberes militares</option>
                                            <option>No tener cargo de pliego ejecutoriado</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Experiencia</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="Escencial" data-off-text="Complementario" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Contar con nacionalidad boliviana</option>
                                            <option>Ser mayor de edad </option>
                                            <option>Haber cumplido con los deberes militares</option>
                                            <option>No tener cargo de pliego ejecutoriado</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Experiencia</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="Escencial" data-off-text="Complementario" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                </div>
      
                <div class="tab-pane " id="tab4">
                     <div class="alert alert-block alert-success fade in">
                        <button type="button" class="close" data-dismiss="alert"></button>
                        <h4 class="alert-heading">Compromiso</h4>
                        <p>
                             Esta seguro de registrar la informacion completa anteriormente?.<br><br>
                        </p>
                        <p>
                            <a class="btn green" href="javascript:;">
                            Aceptar </a>
                        </p>
                    </div>
                </div>
      
                <div class="tab-pane " id="tab5">
                    <div class="col-md-10" >
                        <h3 > <b> 4.1. Objetivos a los que contribuye el puesto</b> </h3>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Código</b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-9">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Descripción</b> </h4>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Codigo del Objetivo </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-9">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Objetivo 1</option>
                                            <option>Objetivo 2 </option>
                                            <option>Objetivo 3</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Descripcion del Objetivo</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Codigo del Objetivo </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-9">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Objetivo 1</option>
                                            <option>Objetivo 2 </option>
                                            <option>Objetivo 3</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Descripcion del Objetivo</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Codigo del Objetivo </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-9">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Objetivo 1</option>
                                            <option>Objetivo 2 </option>
                                            <option>Objetivo 3</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Descripcion del Objetivo</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="col-md-10" >
                        <h3 > <b> 4.2. Operaciones</b> </h3>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Operacion POA</b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Relacion con <br> funcion del Nro <br> del puesto </b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Tipo de Resultado </b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Medio de <br> verificacion</b> </h4>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Operacion 1</option>
                                            <option>Operacion 2 </option>
                                            <option>Operacion 3</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Operacion</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>1</option>
                                            <option>2 </option>
                                            <option>3</option>
                                            <option>...</option>
                                        </select>
                                        <label for="form_control_1">Nro Funcion</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group">
                                        <input type="checkbox" class="make-switch" data-on-text="Recurrente" data-off-text="Producto" data-on-color="success" data-off-color="warning" >
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Documento</option>
                                            <option>Manual</option>
                                            <option>...</option>
                                        </select>
                                        <label for="form_control_1">Medio de Verificacion</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Ponderacion de <br> la Cantidad </b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Ponderacion de <br> la Oportunidad </b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Ponderacion de <br> los Indicadores <br> Cualitativos </b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Ponderacion  <br> Total </b> </h4>
                                </div>
                            </div>
                        </div>
                    </div>
                     <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-5">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">% Cantidad </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                    <input type="text" class="form-control" id="form_control_1">
                                    <label for="form_control_1">% Oportunidad</label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                    <input type="text" class="form-control" id="form_control_1">
                                    <label for="form_control_1">% Indicador Cualitativo </label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                    <input type="text" class="form-control" id="form_control_1">
                                    <label for="form_control_1">% Total por Operación </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-offset-5 col-md-8">
                            <br><button type="button" class="btn red">Añadir</button><br><br>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                             <table class="table table-striped table-hover" id="table_resultados">
                                <thead>
                                    <tr>
                                        <th>
                                             #
                                        </th>
                                        <th>
                                             Operacion <br>POA
                                        </th>
                                        <th>
                                             Relacion <br>con funcion<br> del Nro<br> del Puesto
                                        </th>
                                        <th>
                                             Tipo de <br>Resultado
                                        </th>
                                        <th>
                                             Medio de <br>verificacion
                                        </th>
                                        <th>
                                             Ponderacion<br> de la<br> Cantidad
                                        </th>
                                        <th>
                                             Ponderacion <br>de la<br> Oportunidad
                                        </th>
                                        <th>
                                            Ponderacion<br>de los <br>Indicadores <br>Cualitativos
                                        </th>
                                        <th>
                                             Ponderacion <br>por<br> Operacion
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>
                                             ..
                                        </td>
                                        <td>
                                             ..
                                        </td>
                                        <td>
                                             ..
                                        </td>
                                        <td >
                                             ..
                                        </td>
                                        <td>
                                           ..
                                        </td>
                                            ..
                                        <td>
                                             ..
                                        </td>
                                        <td>
                                            ..
                                        </td>
                                        <td>
                                            ..
                                        </td>
                                        <td>
                                            ..
                                        </td>
                                    </tr>
                                </tbody>
                            </table><br>
                        </div>
                    </div>
                </div>
                <div class="tab-pane " id="tab6">
                    <div class="alert alert-block alert-success fade in">
                        <button type="button" class="close" data-dismiss="alert"></button>
                        <h4 class="alert-heading">Compromiso</h4>
                        <p>
                             Cumplir como mínimo 40 horas de capacitacion durante la presente gestión.<br>
                             La suscripción del POAI supone conformidad dentro del periodo programado, con todo su contenido y compromiso de cumplimiento.
                             Por tal efecto yo, me comprometo con todo lo estipulado en el presente documento.<br><br>
                        </p>
                        <p>
                            <a class="btn green" href="javascript:;">
                            Aceptar </a>
                        </p>
                    </div>
                </div>
         
        </div>
    </div>
</div>

<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="../../assets/global/plugins/respond.min.js"></script>
<script src="../../assets/global/plugins/excanvas.min.js"></script> 
<![endif]-->
<script src="../../assets/global/plugins/jquery.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
<!-- IMPORTANT! Load jquery-ui.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<script src="../../assets/global/plugins/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="../../assets/global/plugins/bootstrap-tabdrop/js/bootstrap-tabdrop.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="../../assets/global/scripts/metronic.js" type="text/javascript"></script>
<script src="../../assets/admin/layout/scripts/layout.js" type="text/javascript"></script>
<script src="../../assets/admin/layout/scripts/quick-sidebar.js" type="text/javascript"></script>
<script src="../../assets/admin/layout/scripts/demo.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script>
jQuery(document).ready(function() {       
   // initiate layout and plugins
   Metronic.init(); // init metronic core components
Layout.init(); // init current layout
QuickSidebar.init(); // init quick sidebar
Demo.init(); // init demo features
});
</script>
<!-- END JAVASCRIPTS -->