<h3 class="page-title">
    POAI <small> </small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="/">Formulacion</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Comenzar POAI</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Nro de Item</a>
        </li>
    </ul>
</div>


<!-- BEGIN PAGE CONTENT-->
<div class="row">
    <div class="col-md-12">
        <div class="portlet box blue" id="form_wizard_1">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i> FORMULACION - <span class="step-title">
								paso 1 de 4 </span>
                </div>
                <div class="tools hidden-xs">
                    <a href="javascript:;" class="collapse">
                    </a>
                    <a href="#portlet-config" data-toggle="modal" class="config">
                    </a>
                    <a href="javascript:;" class="reload">
                    </a>
                    <a href="javascript:;" class="remove">
                    </a>
                </div>
            </div>
            <div class="portlet-body form">
                <form action="#" class="form-horizontal" id="submit_form" method="POST">
                    <div class="form-wizard">
                        <div class="form-body">
                            <ul class="nav nav-pills nav-justified steps">
                                <li>
                                    <a href="#tab1" data-toggle="tab" class="step">
												<span class="number">
												1 </span>
												<span class="desc">
												<i class="fa fa-check"></i> I. Identificación </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#tab2" data-toggle="tab" class="step">
												<span class="number">
												2 </span>
												<span class="desc">
												<i class="fa fa-check"></i> II. Descripción </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#tab3" data-toggle="tab" class="step active">
												<span class="number">
												3 </span>
												<span class="desc">
												<i class="fa fa-check"></i> III. Especificación </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#tab4" data-toggle="tab" class="step">
												<span class="number">
												4 </span>
												<span class="desc">
												<i class="fa fa-check"></i> Confirmación </span>
                                    </a>
                                </li>
                            </ul>
                            <div id="bar" class="progress progress-striped" role="progressbar">
                                <div class="progress-bar progress-bar-success">
                                </div>
                            </div>
                            <div class="tab-content">
                                <div class="alert alert-danger display-none">
                                    <button class="close" data-dismiss="alert"></button>
                                    You have some form errors. Please check below.
                                </div>
                                <div class="alert alert-success display-none">
                                    <button class="close" data-dismiss="alert"></button>
                                    Your form validation is successful!
                                </div>
                                <div class="tab-pane active" id="tab1">

                                    <?php echo $this->unoWidget ?>

                                </div>
                                <div class="tab-pane" id="tab2">
                                    <h3 class="block">Provide your profile details</h3>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">Fullname <span class="required">
													* </span>
                                        </label>
                                        <div class="col-md-4">
                                            <input type="text" class="form-control" name="fullname"/>
														<span class="help-block">
														Provide your fullname </span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">Phone Number <span class="required">
													* </span>
                                        </label>
                                        <div class="col-md-4">
                                            <input type="text" class="form-control" name="phone"/>
														<span class="help-block">
														Provide your phone number </span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">Gender <span class="required">
													* </span>
                                        </label>
                                        <div class="col-md-4">
                                            <div class="radio-list">
                                                <label>
                                                    <input type="radio" name="gender" value="M" data-title="Male"/>
                                                    Male </label>
                                                <label>
                                                    <input type="radio" name="gender" value="F" data-title="Female"/>
                                                    Female </label>
                                            </div>
                                            <div id="form_gender_error">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">Address <span class="required">
													* </span>
                                        </label>
                                        <div class="col-md-4">
                                            <input type="text" class="form-control" name="address"/>
														<span class="help-block">
														Provide your street address </span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">City/Town <span class="required">
													* </span>
                                        </label>
                                        <div class="col-md-4">
                                            <input type="text" class="form-control" name="city"/>
														<span class="help-block">
														Provide your city or town </span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">Country</label>
                                        <div class="col-md-4">
                                            <select name="country" id="country_list" class="form-control">
                                                <option value=""></option>
                                                <option value="AF">Afghanistan</option>
                                                <option value="AL">Albania</option>
                                                <option value="DZ">Algeria</option>
                                                <option value="AS">American Samoa</option>
                                                <option value="AD">Andorra</option>
                                                <option value="AO">Angola</option>
                                                <option value="AI">Anguilla</option>
                                                <option value="AR">Argentina</option>
                                                <option value="AM">Armenia</option>
                                                <option value="AW">Aruba</option>
                                                <option value="AU">Australia</option>
                                                <option value="AT">Austria</option>
                                                <option value="AZ">Azerbaijan</option>
                                                <option value="BS">Bahamas</option>
                                                <option value="BH">Bahrain</option>
                                                <option value="BD">Bangladesh</option>
                                                <option value="BB">Barbados</option>
                                                <option value="BY">Belarus</option>
                                                <option value="BE">Belgium</option>
                                                <option value="BZ">Belize</option>
                                                <option value="BJ">Benin</option>
                                                <option value="BM">Bermuda</option>
                                                <option value="BT">Bhutan</option>
                                                <option value="BO">Bolivia</option>
                                                <option value="BA">Bosnia and Herzegowina</option>
                                                <option value="BW">Botswana</option>
                                                <option value="BV">Bouvet Island</option>
                                                <option value="BR">Brazil</option>
                                                <option value="IO">British Indian Ocean Territory</option>
                                                <option value="BN">Brunei Darussalam</option>
                                                <option value="BG">Bulgaria</option>
                                                <option value="BF">Burkina Faso</option>
                                                <option value="BI">Burundi</option>
                                                <option value="KH">Cambodia</option>
                                                <option value="CM">Cameroon</option>
                                                <option value="CA">Canada</option>
                                                <option value="CV">Cape Verde</option>
                                                <option value="KY">Cayman Islands</option>
                                                <option value="CF">Central African Republic</option>
                                                <option value="TD">Chad</option>
                                                <option value="CL">Chile</option>
                                                <option value="CN">China</option>
                                                <option value="CX">Christmas Island</option>
                                                <option value="CC">Cocos (Keeling) Islands</option>
                                                <option value="CO">Colombia</option>
                                                <option value="KM">Comoros</option>
                                                <option value="CG">Congo</option>
                                                <option value="CD">Congo, the Democratic Republic of the</option>
                                                <option value="CK">Cook Islands</option>
                                                <option value="CR">Costa Rica</option>
                                                <option value="CI">Cote d'Ivoire</option>
                                                <option value="HR">Croatia (Hrvatska)</option>
                                                <option value="CU">Cuba</option>
                                                <option value="CY">Cyprus</option>
                                                <option value="CZ">Czech Republic</option>
                                                <option value="DK">Denmark</option>
                                                <option value="DJ">Djibouti</option>
                                                <option value="DM">Dominica</option>
                                                <option value="DO">Dominican Republic</option>
                                                <option value="EC">Ecuador</option>
                                                <option value="EG">Egypt</option>
                                                <option value="SV">El Salvador</option>
                                                <option value="GQ">Equatorial Guinea</option>
                                                <option value="ER">Eritrea</option>
                                                <option value="EE">Estonia</option>
                                                <option value="ET">Ethiopia</option>
                                                <option value="FK">Falkland Islands (Malvinas)</option>
                                                <option value="FO">Faroe Islands</option>
                                                <option value="FJ">Fiji</option>
                                                <option value="FI">Finland</option>
                                                <option value="FR">France</option>
                                                <option value="GF">French Guiana</option>
                                                <option value="PF">French Polynesia</option>
                                                <option value="TF">French Southern Territories</option>
                                                <option value="GA">Gabon</option>
                                                <option value="GM">Gambia</option>
                                                <option value="GE">Georgia</option>
                                                <option value="DE">Germany</option>
                                                <option value="GH">Ghana</option>
                                                <option value="GI">Gibraltar</option>
                                                <option value="GR">Greece</option>
                                                <option value="GL">Greenland</option>
                                                <option value="GD">Grenada</option>
                                                <option value="GP">Guadeloupe</option>
                                                <option value="GU">Guam</option>
                                                <option value="GT">Guatemala</option>
                                                <option value="GN">Guinea</option>
                                                <option value="GW">Guinea-Bissau</option>
                                                <option value="GY">Guyana</option>
                                                <option value="HT">Haiti</option>
                                                <option value="HM">Heard and Mc Donald Islands</option>
                                                <option value="VA">Holy See (Vatican City State)</option>
                                                <option value="HN">Honduras</option>
                                                <option value="HK">Hong Kong</option>
                                                <option value="HU">Hungary</option>
                                                <option value="IS">Iceland</option>
                                                <option value="IN">India</option>
                                                <option value="ID">Indonesia</option>
                                                <option value="IR">Iran (Islamic Republic of)</option>
                                                <option value="IQ">Iraq</option>
                                                <option value="IE">Ireland</option>
                                                <option value="IL">Israel</option>
                                                <option value="IT">Italy</option>
                                                <option value="JM">Jamaica</option>
                                                <option value="JP">Japan</option>
                                                <option value="JO">Jordan</option>
                                                <option value="KZ">Kazakhstan</option>
                                                <option value="KE">Kenya</option>
                                                <option value="KI">Kiribati</option>
                                                <option value="KP">Korea, Democratic People's Republic of</option>
                                                <option value="KR">Korea, Republic of</option>
                                                <option value="KW">Kuwait</option>
                                                <option value="KG">Kyrgyzstan</option>
                                                <option value="LA">Lao People's Democratic Republic</option>
                                                <option value="LV">Latvia</option>
                                                <option value="LB">Lebanon</option>
                                                <option value="LS">Lesotho</option>
                                                <option value="LR">Liberia</option>
                                                <option value="LY">Libyan Arab Jamahiriya</option>
                                                <option value="LI">Liechtenstein</option>
                                                <option value="LT">Lithuania</option>
                                                <option value="LU">Luxembourg</option>
                                                <option value="MO">Macau</option>
                                                <option value="MK">Macedonia, The Former Yugoslav Republic of</option>
                                                <option value="MG">Madagascar</option>
                                                <option value="MW">Malawi</option>
                                                <option value="MY">Malaysia</option>
                                                <option value="MV">Maldives</option>
                                                <option value="ML">Mali</option>
                                                <option value="MT">Malta</option>
                                                <option value="MH">Marshall Islands</option>
                                                <option value="MQ">Martinique</option>
                                                <option value="MR">Mauritania</option>
                                                <option value="MU">Mauritius</option>
                                                <option value="YT">Mayotte</option>
                                                <option value="MX">Mexico</option>
                                                <option value="FM">Micronesia, Federated States of</option>
                                                <option value="MD">Moldova, Republic of</option>
                                                <option value="MC">Monaco</option>
                                                <option value="MN">Mongolia</option>
                                                <option value="MS">Montserrat</option>
                                                <option value="MA">Morocco</option>
                                                <option value="MZ">Mozambique</option>
                                                <option value="MM">Myanmar</option>
                                                <option value="NA">Namibia</option>
                                                <option value="NR">Nauru</option>
                                                <option value="NP">Nepal</option>
                                                <option value="NL">Netherlands</option>
                                                <option value="AN">Netherlands Antilles</option>
                                                <option value="NC">New Caledonia</option>
                                                <option value="NZ">New Zealand</option>
                                                <option value="NI">Nicaragua</option>
                                                <option value="NE">Niger</option>
                                                <option value="NG">Nigeria</option>
                                                <option value="NU">Niue</option>
                                                <option value="NF">Norfolk Island</option>
                                                <option value="MP">Northern Mariana Islands</option>
                                                <option value="NO">Norway</option>
                                                <option value="OM">Oman</option>
                                                <option value="PK">Pakistan</option>
                                                <option value="PW">Palau</option>
                                                <option value="PA">Panama</option>
                                                <option value="PG">Papua New Guinea</option>
                                                <option value="PY">Paraguay</option>
                                                <option value="PE">Peru</option>
                                                <option value="PH">Philippines</option>
                                                <option value="PN">Pitcairn</option>
                                                <option value="PL">Poland</option>
                                                <option value="PT">Portugal</option>
                                                <option value="PR">Puerto Rico</option>
                                                <option value="QA">Qatar</option>
                                                <option value="RE">Reunion</option>
                                                <option value="RO">Romania</option>
                                                <option value="RU">Russian Federation</option>
                                                <option value="RW">Rwanda</option>
                                                <option value="KN">Saint Kitts and Nevis</option>
                                                <option value="LC">Saint LUCIA</option>
                                                <option value="VC">Saint Vincent and the Grenadines</option>
                                                <option value="WS">Samoa</option>
                                                <option value="SM">San Marino</option>
                                                <option value="ST">Sao Tome and Principe</option>
                                                <option value="SA">Saudi Arabia</option>
                                                <option value="SN">Senegal</option>
                                                <option value="SC">Seychelles</option>
                                                <option value="SL">Sierra Leone</option>
                                                <option value="SG">Singapore</option>
                                                <option value="SK">Slovakia (Slovak Republic)</option>
                                                <option value="SI">Slovenia</option>
                                                <option value="SB">Solomon Islands</option>
                                                <option value="SO">Somalia</option>
                                                <option value="ZA">South Africa</option>
                                                <option value="GS">South Georgia and the South Sandwich Islands</option>
                                                <option value="ES">Spain</option>
                                                <option value="LK">Sri Lanka</option>
                                                <option value="SH">St. Helena</option>
                                                <option value="PM">St. Pierre and Miquelon</option>
                                                <option value="SD">Sudan</option>
                                                <option value="SR">Suriname</option>
                                                <option value="SJ">Svalbard and Jan Mayen Islands</option>
                                                <option value="SZ">Swaziland</option>
                                                <option value="SE">Sweden</option>
                                                <option value="CH">Switzerland</option>
                                                <option value="SY">Syrian Arab Republic</option>
                                                <option value="TW">Taiwan, Province of China</option>
                                                <option value="TJ">Tajikistan</option>
                                                <option value="TZ">Tanzania, United Republic of</option>
                                                <option value="TH">Thailand</option>
                                                <option value="TG">Togo</option>
                                                <option value="TK">Tokelau</option>
                                                <option value="TO">Tonga</option>
                                                <option value="TT">Trinidad and Tobago</option>
                                                <option value="TN">Tunisia</option>
                                                <option value="TR">Turkey</option>
                                                <option value="TM">Turkmenistan</option>
                                                <option value="TC">Turks and Caicos Islands</option>
                                                <option value="TV">Tuvalu</option>
                                                <option value="UG">Uganda</option>
                                                <option value="UA">Ukraine</option>
                                                <option value="AE">United Arab Emirates</option>
                                                <option value="GB">United Kingdom</option>
                                                <option value="US">United States</option>
                                                <option value="UM">United States Minor Outlying Islands</option>
                                                <option value="UY">Uruguay</option>
                                                <option value="UZ">Uzbekistan</option>
                                                <option value="VU">Vanuatu</option>
                                                <option value="VE">Venezuela</option>
                                                <option value="VN">Viet Nam</option>
                                                <option value="VG">Virgin Islands (British)</option>
                                                <option value="VI">Virgin Islands (U.S.)</option>
                                                <option value="WF">Wallis and Futuna Islands</option>
                                                <option value="EH">Western Sahara</option>
                                                <option value="YE">Yemen</option>
                                                <option value="ZM">Zambia</option>
                                                <option value="ZW">Zimbabwe</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">Remarks</label>
                                        <div class="col-md-4">
                                            <textarea class="form-control" rows="3" name="remarks"></textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane" id="tab3">
                                    <h3 class="block">Provide your billing and credit card details</h3>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">Card Holder Name <span class="required">
													* </span>
                                        </label>
                                        <div class="col-md-4">
                                            <input type="text" class="form-control" name="card_name"/>
														<span class="help-block">
														</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">Card Number <span class="required">
													* </span>
                                        </label>
                                        <div class="col-md-4">
                                            <input type="text" class="form-control" name="card_number"/>
														<span class="help-block">
														</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">CVC <span class="required">
													* </span>
                                        </label>
                                        <div class="col-md-4">
                                            <input type="text" placeholder="" class="form-control" name="card_cvc"/>
														<span class="help-block">
														</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">Expiration(MM/YYYY) <span class="required">
													* </span>
                                        </label>
                                        <div class="col-md-4">
                                            <input type="text" placeholder="MM/YYYY" maxlength="7" class="form-control" name="card_expiry_date"/>
														<span class="help-block">
														e.g 11/2020 </span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">Payment Options <span class="required">
													* </span>
                                        </label>
                                        <div class="col-md-4">
                                            <div class="checkbox-list">
                                                <label>
                                                    <input type="checkbox" name="payment[]" value="1" data-title="Auto-Pay with this Credit Card."/> Auto-Pay with this Credit Card </label>
                                                <label>
                                                    <input type="checkbox" name="payment[]" value="2" data-title="Email me monthly billing."/> Email me monthly billing </label>
                                            </div>
                                            <div id="form_payment_error">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane" id="tab4">
                                    <h3 class="block">Confirm your account</h3>
                                    <h4 class="form-section">Account</h4>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">Username:</label>
                                        <div class="col-md-4">
                                            <p class="form-control-static" data-display="username">
                                            </p>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">Email:</label>
                                        <div class="col-md-4">
                                            <p class="form-control-static" data-display="email">
                                            </p>
                                        </div>
                                    </div>
                                    <h4 class="form-section">Profile</h4>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">Fullname:</label>
                                        <div class="col-md-4">
                                            <p class="form-control-static" data-display="fullname">
                                            </p>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">Gender:</label>
                                        <div class="col-md-4">
                                            <p class="form-control-static" data-display="gender">
                                            </p>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">Phone:</label>
                                        <div class="col-md-4">
                                            <p class="form-control-static" data-display="phone">
                                            </p>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">Address:</label>
                                        <div class="col-md-4">
                                            <p class="form-control-static" data-display="address">
                                            </p>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">City/Town:</label>
                                        <div class="col-md-4">
                                            <p class="form-control-static" data-display="city">
                                            </p>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">Country:</label>
                                        <div class="col-md-4">
                                            <p class="form-control-static" data-display="country">
                                            </p>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">Remarks:</label>
                                        <div class="col-md-4">
                                            <p class="form-control-static" data-display="remarks">
                                            </p>
                                        </div>
                                    </div>
                                    <h4 class="form-section">Billing</h4>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">Card Holder Name:</label>
                                        <div class="col-md-4">
                                            <p class="form-control-static" data-display="card_name">
                                            </p>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">Card Number:</label>
                                        <div class="col-md-4">
                                            <p class="form-control-static" data-display="card_number">
                                            </p>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">CVC:</label>
                                        <div class="col-md-4">
                                            <p class="form-control-static" data-display="card_cvc">
                                            </p>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">Expiration:</label>
                                        <div class="col-md-4">
                                            <p class="form-control-static" data-display="card_expiry_date">
                                            </p>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3">Payment Options:</label>
                                        <div class="col-md-4">
                                            <p class="form-control-static" data-display="payment[]">
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-offset-3 col-md-9">
                                    <a href="javascript:;" class="btn default button-previous">
                                        <i class="m-icon-swapleft"></i>
                                        Atras </a>
                                    <a href="javascript:;" class="btn blue button-next">
                                        Continuar <i class="m-icon-swapright m-icon-white"></i>
                                    </a>
                                    <a href="javascript:;" class="btn green button-submit">
                                        Enviar <i class="m-icon-swapright m-icon-white"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- END PAGE CONTENT-->

<link rel="stylesheet" type="text/css" href="../../assets/global/plugins/select2/select2.css"/>
<script type="text/javascript" src="/assets/global/plugins/jquery-validation/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="/assets/global/plugins/jquery-validation/js/additional-methods.min.js"></script>
<script type="text/javascript" src="/assets/global/plugins/bootstrap-wizard/jquery.bootstrap.wizard.min.js"></script>
<script type="text/javascript" src="/assets/global/plugins/select2/select2.min.js"></script>

<script>
    jQuery(document).ready(function() {
        FormWizard.init();
    });
</script>









<div class="portlet box red" style="display: none">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i> Planificacion Operativa Anual Individual
        </div>
        <div class="tools">
            <a href="" class="reload"></a>
        </div>
    </div>
      <div class="portlet-body form">
        <div class="tabbable tabbable-tabdrop">
            <ul class="nav nav-tabs">
                <li class="active">
                    <a href="#tab1" data-toggle="tab">I. Identificación</a>
                </li>
                <li>
                    <a href="#tab2" data-toggle="tab">II. Descripción</a>
                </li>
                <li>
                    <a href="#tab3" data-toggle="tab">III. Especificación</a>
                </li>
                <li>
                    <a href="#tab4" data-toggle="tab">Confirmacion</a>
                </li>
                <li>
                    <a href="#tab5" data-toggle="tab">IV. Resultados Esperados</a>
                </li>
                <li>
                    <a href="#tab6" data-toggle="tab">V. Compromiso</a>
                </li>
       

            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="tab1">

                    <div class="col-md-10" >
                        <h3 > <b> 1.1. Datos del Puesto </b> </h3>
                    </div>

                    <form class="form-horizontal" role="form">

                        <div class="form-group">
                            <label for="text" class="col-md-4 control-label">Nro de Item: </label>
                            <div class="col-md-8">
                                </br><label for = "denominacion_cargo" id="lab_denominacion_cargo"> 301 </label>
                            </div>

                            <label for="text" class="col-md-4 control-label">Nivel: </label>
                            <div class="col-md-8">
                                </br><label for = "denominacion_cargo" id="lab_denominacion_cargo"> 5 </label>
                            </div>

                            <label for="text" class="col-md-4 control-label">Categoría: </label>
                            <div class="col-md-8">
                                </br><label for = "denominacion_cargo" id="lab_denominacion_cargo"> OPERATIVO </label>
                            </div>

                            <label for="text" class="col-md-4 control-label">Denominación del cargo: </label>
                            <div class="col-md-8">
                                </br><label for = "denominacion_cargo" id="lab_denominacion_cargo"> PROFESIONAL II </label>
                            </div>
                    
                            <label for="text" class="col-md-4 control-label">Denominacion del puesto: </label>
                            <div class="col-md-8">
                                </br><label for = "denominacion_puesto" id="lab_denominacion_puesto"> RESPONSABLE DE MOVILIDAD Y REGISTRO DE PERSONAL </label>
                            </div>

                            <label for="text" class="col-md-4 control-label">Dependencia: </label>
                            <div class="col-md-8">
                                </br><label for = "dependencia" id="lab_dependencia"> UNIDAD DE RECURSOS HUMANOS</label>
                            </div>
                        </div>
                    </form>

                    <hr>

                    <div class="col-md-15" >
                        <h3> &nbsp <b> 1.2. Relaciones del Puesto </b> </h3>
                    </div> 
                    <div class="col-md-15" >
                        <h4> &nbsp &nbsp <b>1.2.1. Relaciones Jerárquicas </b></h4></br>
                    </div>


                    <div class="form-group">

                        <div class="col-md-5">
                            <div class="form-group form-md-line-input form-md-floating-label has-error">
                                <input type="text" class="form-control" id="form_control_1">
                                <label for="form_control_1">Depende de: </label>
                            </div>
                        </div>

                        <div class="col-md-5">
                            <div class="form-group form-md-line-input form-md-floating-label has-error">
                                <input type="text" class="form-control" id="form_control_1">
                                <label for="form_control_1">Supervisa a: </label>
                            </div>
                            <div class="form-group form-md-line-input form-md-floating-label has-error">
                                <input type="text" class="form-control" id="form_control_1">
                                <label for="form_control_1">Supervisa a: </label>
                            </div>
                            <div class="form-group form-md-line-input form-md-floating-label has-error">
                                <input type="text" class="form-control" id="form_control_1">
                                <label for="form_control_1">Supervisa a: </label>
                            </div>
                          
                        </div>
                        <div class="col-md-1">
                            <div class="form-group form-md-line-input form-md-floating-label has-error">
                                <input type="text" class="form-control" id="form_control_1">
                                <label for="form_control_1">Cantidad: </label>
                            </div>
                            <div class="form-group form-md-line-input form-md-floating-label has-error">
                                <input type="text" class="form-control" id="form_control_1">
                                <label for="form_control_1">Cantidad: </label>
                            </div>
                            <div class="form-group form-md-line-input form-md-floating-label has-error">
                                <input type="text" class="form-control" id="form_control_1">
                                <label for="form_control_1">Cantidad: </label>
                            </div>
                        </br></br></br>
                        </div>
                    </div>
                   
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> 1.2.2. Relaciones Intrainstitucionales </b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b>  1.2.3. Relaciones Interinstitucionales </b> </h4>
                                </div>
                            </div>
                        </div>
                    </div> 

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">1. </label>
                                    </div>            
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">2. </label>
                                    </div>
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">3. </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">1. </label>
                                    </div>
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">2. </label>
                                    </div>
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">3. </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div> 

                </div>
            
    
                <div class="tab-pane " id="tab2">

                    <div class="col-md-10" >
                        <h3 > <b> 2.1. Objetivo del Puesto </b> </h3>
                    </div>
                    <form class="col-md-14">
                        <div class="form-group">
                            <div class="col-md-11">
                               <div class="form-group form-md-line-input form-md-floating-label has-error">
                                    <textarea class="form-control" rows="1"></textarea>
                                    <label for="form_control_1">Que hace?</label>
                                </div>
                           </div>
                        </div>
                        <div class="form-group">
                           <div class="col-md-11">
                               <div class="form-group form-md-line-input form-md-floating-label has-error">
                                    <textarea class="form-control" rows="1"></textarea>
                                    <label for="form_control_1">De que forma?</label>
                                </div>
                           </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-11">
                               <div class="form-group form-md-line-input form-md-floating-label has-error">
                                    <textarea class="form-control" rows="1"></textarea>
                                    <label for="form_control_1">Con que finalidad?</label>
                                </div>
                           </div>
                        </div>
                    </form>

                    <div class="col-md-10" >
                        <h3 > <b> 2.2. Normas a Cumplir </b> </h3>
                    </div >
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Normas Generales </b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b>  Normas Especificas</b> </h4>
                                </div>
                            </div>
                        </div>
                    </div>
                   
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option value="1">Option 1</option>
                                            <option value="2">Option 2</option>
                                            <option value="3">Option 3</option>
                                            <option value="4">Option 4</option>
                                        </select>
                                        <label for="form_control_1">Norma General</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--/span-->
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option value="1">Option 1</option>
                                            <option value="2">Option 2</option>
                                            <option value="3">Option 3</option>
                                            <option value="4">Option 4</option>
                                        </select>
                                        <label for="form_control_1">Norma Especifica</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                  
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option value="1">Option 1</option>
                                            <option value="2">Option 2</option>
                                            <option value="3">Option 3</option>
                                            <option value="4">Option 4</option>
                                        </select>
                                        <label for="form_control_1">Norma General</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--/span-->
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option value="1">Option 1</option>
                                            <option value="2">Option 2</option>
                                            <option value="3">Option 3</option>
                                            <option value="4">Option 4</option>
                                        </select>
                                        <label for="form_control_1">Norma Especifica</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option value="1">Option 1</option>
                                            <option value="2">Option 2</option>
                                            <option value="3">Option 3</option>
                                            <option value="4">Option 4</option>
                                        </select>
                                        <label for="form_control_1">Norma General</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--/span-->
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option value="1">Option 1</option>
                                            <option value="2">Option 2</option>
                                            <option value="3">Option 3</option>
                                            <option value="4">Option 4</option>
                                        </select>
                                        <label for="form_control_1">Norma Especifica</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option value="1">Option 1</option>
                                            <option value="2">Option 2</option>
                                            <option value="3">Option 3</option>
                                            <option value="4">Option 4</option>
                                        </select>
                                        <label for="form_control_1">Norma General</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--/span-->
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option value="1">Option 1</option>
                                            <option value="2">Option 2</option>
                                            <option value="3">Option 3</option>
                                            <option value="4">Option 4</option>
                                        </select>
                                        <label for="form_control_1">Norma Especifica</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option value="1">Option 1</option>
                                            <option value="2">Option 2</option>
                                            <option value="3">Option 3</option>
                                            <option value="4">Option 4</option>
                                        </select>
                                        <label for="form_control_1">Norma General</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--/span-->
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option value="1">Option 1</option>
                                            <option value="2">Option 2</option>
                                            <option value="3">Option 3</option>
                                            <option value="4">Option 4</option>
                                        </select>
                                        <label for="form_control_1">Norma Especifica</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-10" >
                        <h3 > <b> 2.3. Funciones del Puesto </b> </h3>
                    </div>
                    <div class="col-md-10" >
                            <h4 > <b>  Funciones Generales del Puesto </b> </h4>           
                    </div>
                    <form action="#" class="horizontal-form">  
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">1. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">2. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">3. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">4. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">5. </label>
                                                </div>
                                            </div>
                                        </div>                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">6. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">7. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">8. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">9. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">10. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                </form>         
                                <div class="col-md-10" >
                                    <h4 > <b>  Funciones Especificas del Puesto </b> </h4>
                                </div>
                                <form action="#" class="horizontal-form">  
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">1. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">2. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">3. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">4. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">5. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">6. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">7. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                               <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">8. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">9. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <div class="col-md-10" >
                                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                                    <input type="text" class="form-control" id="form_control_1">
                                                    <label for="form_control_1">10. </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="checkbox" class="make-switch" data-on-text="&nbsp;Recurrente&nbsp;" data-off-text="&nbsp;Producto&nbsp;" data-on-color="success" data-off-color="warning" >
                                            </div>
                                        </div>  
                                    </div>

                                </form>
                </div>
     
                <div class="tab-pane " id="tab3">

                     <div class="col-md-10" >
                        <h3 > <b> 3.1. Formación </b> </h3>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Area de Formación </b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b>  Grado de Formación <br> Mínima Aceptable</b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Prioridad</b> </h4>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-11" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Area de Formación </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-15" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Estudiante de Secundaria y/o Primaria</option>
                                            <option>Bachiller</option>
                                            <option>Técnico Medio y/0 Estudiante Universitario (3er Año Vencido)</option>
                                            <option>Técnico Superior Univesitario con Conclusion de Plan de Estudios</option>
                                            <option>Licenciatura</option>
                                            <option>Diplomado</option>
                                            <option>Especialización</option>
                                            <option>Maestría</option>
                                        </select>
                                        <label for="form_control_1">Norma General</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="&nbsp;Escencial&nbsp;" data-off-text="&nbsp;Complementario&nbsp;" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-11" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Area de Formación </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-15" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Estudiante de Secundaria y/o Primaria</option>
                                            <option>Bachiller</option>
                                            <option>Técnico Medio y/0 Estudiante Universitario (3er Año Vencido)</option>
                                            <option>Técnico Superior Univesitario con Conclusion de Plan de Estudios</option>
                                            <option>Licenciatura</option>
                                            <option>Diplomado</option>
                                            <option>Especialización</option>
                                            <option>Maestría</option>
                                        </select>
                                        <label for="form_control_1">Norma General</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="&nbsp;Escencial&nbsp;" data-off-text="&nbsp;Complementario&nbsp;" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-11" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Area de Formación </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-15" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Estudiante de Secundaria y/o Primaria</option>
                                            <option>Bachiller</option>
                                            <option>Técnico Medio y/0 Estudiante Universitario (3er Año Vencido)</option>
                                            <option>Técnico Superior Univesitario con Conclusion de Plan de Estudios</option>
                                            <option>Licenciatura</option>
                                            <option>Diplomado</option>
                                            <option>Especialización</option>
                                            <option>Maestría</option>
                                        </select>
                                        <label for="form_control_1">Norma General</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="&nbsp;Escencial&nbsp;" data-off-text="&nbsp;Complementario&nbsp;" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-11" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Area de Formación </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-15" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Estudiante de Secundaria y/o Primaria</option>
                                            <option>Bachiller</option>
                                            <option>Técnico Medio y/0 Estudiante Universitario (3er Año Vencido)</option>
                                            <option>Técnico Superior Univesitario con Conclusion de Plan de Estudios</option>
                                            <option>Licenciatura</option>
                                            <option>Diplomado</option>
                                            <option>Especialización</option>
                                            <option>Maestría</option>
                                        </select>
                                        <label for="form_control_1">Norma General</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="&nbsp;Escencial&nbsp;" data-off-text="&nbsp;Complementario&nbsp;" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-11" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Area de Formación </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-15" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Estudiante de Secundaria y/o Primaria</option>
                                            <option>Bachiller</option>
                                            <option>Técnico Medio y/0 Estudiante Universitario (3er Año Vencido)</option>
                                            <option>Técnico Superior Univesitario con Conclusion de Plan de Estudios</option>
                                            <option>Licenciatura</option>
                                            <option>Diplomado</option>
                                            <option>Especialización</option>
                                            <option>Maestría</option>
                                        </select>
                                        <label for="form_control_1">Norma General</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="&nbsp;Escencial&nbsp;" data-off-text="&nbsp;Complementario&nbsp;" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>

                    <div class="col-md-10" >
                        <h3 > <b> 3.2. Experiencia </b> </h3>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Area de Experiencia </b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Experiencia </b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Sector <br> (y/o)</b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Prioridad</b> </h4>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Area de Experiencia </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                               <div class="form-group form-md-line-input form-md-floating-label has-error">
                                    <select class="form-control" id="form_control_1">
                                        <option value=""></option>
                                        <option>Laboral</option>
                                        <option>Profesional</option>
                                        <option>General</option>
                                        <option>Especifico</option>
                                    </select>
                                    <label for="form_control_1">Experiencia</label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="form-group form-md-line-input">
                                    <div class="col-md-10">
                                        <div class="md-checkbox">
                                            <div class="md-checkbox has-success">
                                                <input type="checkbox" id="checkbox1" class="md-check">
                                                <label for="checkbox1">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Publica</label>
                                            </div>
                                            <div class="md-checkbox has-warning">
                                                <input type="checkbox" id="checkbox2" class="md-check" >
                                                <label for="checkbox2">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Privada</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="Escencial" data-off-text="Complementario" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Area de Experiencia </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                               <div class="form-group form-md-line-input form-md-floating-label has-error">
                                    <select class="form-control" id="form_control_1">
                                        <option value=""></option>
                                        <option>Laboral</option>
                                        <option>Profesional</option>
                                        <option>General</option>
                                        <option>Especifico</option>
                                    </select>
                                    <label for="form_control_1">Experiencia</label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="form-group form-md-line-input">
                                    <div class="col-md-10">
                                        <div class="md-checkbox">
                                            <div class="md-checkbox has-success">
                                                <input type="checkbox" id="checkbox3" class="md-check">
                                                <label for="checkbox3">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Publica</label>
                                            </div>
                                            <div class="md-checkbox has-warning">
                                                <input type="checkbox" id="checkbox4" class="md-check" >
                                                <label for="checkbox4">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Privada</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="Escencial" data-off-text="Complementario" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Area de Experiencia </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                               <div class="form-group form-md-line-input form-md-floating-label has-error">
                                    <select class="form-control" id="form_control_1">
                                        <option value=""></option>
                                        <option>Laboral</option>
                                        <option>Profesional</option>
                                        <option>General</option>
                                        <option>Especifico</option>
                                    </select>
                                    <label for="form_control_1">Experiencia</label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="form-group form-md-line-input">
                                    <div class="col-md-10">
                                        <div class="md-checkbox">
                                            <div class="md-checkbox has-success">
                                                <input type="checkbox" id="checkbox5" class="md-check">
                                                <label for="checkbox5">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Publica</label>
                                            </div>
                                            <div class="md-checkbox has-warning">
                                                <input type="checkbox" id="checkbox6" class="md-check" >
                                                <label for="checkbox6">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Privada</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="Escencial" data-off-text="Complementario" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Area de Experiencia </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                               <div class="form-group form-md-line-input form-md-floating-label has-error">
                                    <select class="form-control" id="form_control_1">
                                        <option value=""></option>
                                        <option>Laboral</option>
                                        <option>Profesional</option>
                                        <option>General</option>
                                        <option>Especifico</option>
                                    </select>
                                    <label for="form_control_1">Experiencia</label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="form-group form-md-line-input">
                                    <div class="col-md-10">
                                        <div class="md-checkbox">
                                            <div class="md-checkbox has-success">
                                                <input type="checkbox" id="checkbox7" class="md-check">
                                                <label for="checkbox7">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Publica</label>
                                            </div>
                                            <div class="md-checkbox has-warning">
                                                <input type="checkbox" id="checkbox8" class="md-check" >
                                                <label for="checkbox8">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Privada</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="Escencial" data-off-text="Complementario" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Area de Experiencia </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                               <div class="form-group form-md-line-input form-md-floating-label has-error">
                                    <select class="form-control" id="form_control_1">
                                        <option value=""></option>
                                        <option>Laboral</option>
                                        <option>Profesional</option>
                                        <option>General</option>
                                        <option>Especifico</option>
                                    </select>
                                    <label for="form_control_1">Experiencia</label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="form-group form-md-line-input">
                                    <div class="col-md-10">
                                        <div class="md-checkbox">
                                            <div class="md-checkbox has-success">
                                                <input type="checkbox" id="checkbox9" class="md-check">
                                                <label for="checkbox9">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Publica</label>
                                            </div>
                                            <div class="md-checkbox has-warning">
                                                <input type="checkbox" id="checkbox10" class="md-check" >
                                                <label for="checkbox10">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Privada</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="Escencial" data-off-text="Complementario" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="col-md-10" >
                        <h3 > <b> 3.3. Registro Profesional </b> </h3>
                    </div>
                    <div class="col-md-11">
                        <div class="form-group form-md-line-input form-md-floating-label has-error">
                            <textarea class="form-control" rows="1"></textarea>
                            <label for="form_control_1">Escriba si es necesario cuando el puesto así lo requiera para el ejercicio de una profesión.</label>
                        </div>
                    </div>
                    <div class="col-md-10" >
                        <h3 > <b> 3.4. Competencias </b> </h3>
                    </div>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Competencias</b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-7">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Descripción</b> </h4>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Liderazgo</option>
                                            <option>Planificacion y Organizacion </option>
                                            <option>Habilidad de control</option>
                                            <option>Delegacion</option>
                                            <option>Desarrollo de los subordinados, equipo u otras personas</option>
                                            <option>Capacidad Critica</option>
                                            <option>Capacidad de decision</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Experiencia</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-7">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Descripcion </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Liderazgo</option>
                                            <option>Planificacion y Organizacion </option>
                                            <option>Habilidad de control</option>
                                            <option>Delegacion</option>
                                            <option>Desarrollo de los subordinados, equipo u otras personas</option>
                                            <option>Capacidad Critica</option>
                                            <option>Capacidad de decision</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Experiencia</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-7">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Descripcion </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Liderazgo</option>
                                            <option>Planificacion y Organizacion </option>
                                            <option>Habilidad de control</option>
                                            <option>Delegacion</option>
                                            <option>Desarrollo de los subordinados, equipo u otras personas</option>
                                            <option>Capacidad Critica</option>
                                            <option>Capacidad de decision</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Experiencia</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-7">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Descripcion </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Liderazgo</option>
                                            <option>Planificacion y Organizacion </option>
                                            <option>Habilidad de control</option>
                                            <option>Delegacion</option>
                                            <option>Desarrollo de los subordinados, equipo u otras personas</option>
                                            <option>Capacidad Critica</option>
                                            <option>Capacidad de decision</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Experiencia</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-7">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Descripcion </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Liderazgo</option>
                                            <option>Planificacion y Organizacion </option>
                                            <option>Habilidad de control</option>
                                            <option>Delegacion</option>
                                            <option>Desarrollo de los subordinados, equipo u otras personas</option>
                                            <option>Capacidad Critica</option>
                                            <option>Capacidad de decision</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Experiencia</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-7">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Descripcion </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-10" >
                        <h3 > <b> 3.5. Conocimientos Requeridos </b> </h3>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Descripción</b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <h4 > <b> Nivel</b> </h4>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <h4 > <b> Prioridad</b> </h4>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-12">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Descripcion </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="form-group form-md-line-input">
                                    <div class="col-md-10">
                                        <div class="md-radio-inline">
                                            <div class="md-radio has-error">
                                                <input type="radio" id="radio1" name="radio2" class="md-radiobtn">
                                                <label for="radio1">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Basico</label>
                                            </div>
                                            <div class="md-radio has-success">
                                                <input type="radio" id="radio2" name="radio2" class="md-radiobtn" >
                                                <label for="radio2">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Intermedio</label>
                                            </div>
                                            <div class="md-radio has-warning">
                                                <input type="radio" id="radio3" name="radio2" class="md-radiobtn">
                                                <label for="radio3">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Avanzado</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="Escencial" data-off-text="Complementario" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-12">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Descripcion </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="form-group form-md-line-input">
                                    <div class="col-md-10">
                                        <div class="md-radio-inline">
                                            <div class="md-radio has-error">
                                                <input type="radio" id="radio1" name="radio2" class="md-radiobtn">
                                                <label for="radio1">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Basico</label>
                                            </div>
                                            <div class="md-radio has-success">
                                                <input type="radio" id="radio2" name="radio2" class="md-radiobtn" >
                                                <label for="radio2">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Intermedio</label>
                                            </div>
                                            <div class="md-radio has-warning">
                                                <input type="radio" id="radio3" name="radio2" class="md-radiobtn">
                                                <label for="radio3">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Avanzado</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="Escencial" data-off-text="Complementario" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-12">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Descripcion </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <div class="form-group form-md-line-input">
                                    <div class="col-md-10">
                                        <div class="md-radio-inline">
                                            <div class="md-radio has-error">
                                                <input type="radio" id="radio1" name="radio2" class="md-radiobtn">
                                                <label for="radio1">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Basico</label>
                                            </div>
                                            <div class="md-radio has-success">
                                                <input type="radio" id="radio2" name="radio2" class="md-radiobtn" >
                                                <label for="radio2">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Intermedio</label>
                                            </div>
                                            <div class="md-radio has-warning">
                                                <input type="radio" id="radio3" name="radio2" class="md-radiobtn">
                                                <label for="radio3">
                                                <span></span>
                                                <span class="check"></span>
                                                <span class="box"></span>
                                                Avanzado</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="Escencial" data-off-text="Complementario" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>

                    <div class="col-md-10" >
                        <h3 > <b> 3.6. Requisitos Constitucionales</b> </h3>
                    </div>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Descripción</b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Prioridad</b> </h4>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Contar con nacionalidad boliviana</option>
                                            <option>Ser mayor de edad </option>
                                            <option>Haber cumplido con los deberes militares</option>
                                            <option>No tener cargo de pliego ejecutoriado</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Experiencia</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="Escencial" data-off-text="Complementario" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Contar con nacionalidad boliviana</option>
                                            <option>Ser mayor de edad </option>
                                            <option>Haber cumplido con los deberes militares</option>
                                            <option>No tener cargo de pliego ejecutoriado</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Experiencia</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="Escencial" data-off-text="Complementario" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Contar con nacionalidad boliviana</option>
                                            <option>Ser mayor de edad </option>
                                            <option>Haber cumplido con los deberes militares</option>
                                            <option>No tener cargo de pliego ejecutoriado</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Experiencia</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <br><input type="checkbox" class="make-switch" data-on-text="Escencial" data-off-text="Complementario" data-on-color="success" data-off-color="warning" >
                            </div>
                        </div>
                    </div>
                </div>
      
                <div class="tab-pane " id="tab4">
                     <div class="alert alert-block alert-success fade in">
                        <button type="button" class="close" data-dismiss="alert"></button>
                        <h4 class="alert-heading">Compromiso</h4>
                        <p>
                             Esta seguro de registrar la informacion completa anteriormente?.<br><br>
                        </p>
                        <p>
                            <a class="btn green" href="javascript:;">
                            Aceptar </a>
                        </p>
                    </div>
                </div>
      
                <div class="tab-pane " id="tab5">
                    <div class="col-md-10" >
                        <h3 > <b> 4.1. Objetivos a los que contribuye el puesto</b> </h3>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Código</b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-9">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Descripción</b> </h4>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Codigo del Objetivo </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-9">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Objetivo 1</option>
                                            <option>Objetivo 2 </option>
                                            <option>Objetivo 3</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Descripcion del Objetivo</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Codigo del Objetivo </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-9">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Objetivo 1</option>
                                            <option>Objetivo 2 </option>
                                            <option>Objetivo 3</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Descripcion del Objetivo</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">Codigo del Objetivo </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-9">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Objetivo 1</option>
                                            <option>Objetivo 2 </option>
                                            <option>Objetivo 3</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Descripcion del Objetivo</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="col-md-10" >
                        <h3 > <b> 4.2. Operaciones</b> </h3>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Operacion POA</b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Relacion con <br> funcion del Nro <br> del puesto </b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Tipo de Resultado </b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Medio de <br> verificacion</b> </h4>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Operacion 1</option>
                                            <option>Operacion 2 </option>
                                            <option>Operacion 3</option>
                                            <option>.....</option>
                                        </select>
                                        <label for="form_control_1">Operacion</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>1</option>
                                            <option>2 </option>
                                            <option>3</option>
                                            <option>...</option>
                                        </select>
                                        <label for="form_control_1">Nro Funcion</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group">
                                        <input type="checkbox" class="make-switch" data-on-text="Recurrente" data-off-text="Producto" data-on-color="success" data-off-color="warning" >
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <select class="form-control" id="form_control_1">
                                            <option value=""></option>
                                            <option>Documento</option>
                                            <option>Manual</option>
                                            <option>...</option>
                                        </select>
                                        <label for="form_control_1">Medio de Verificacion</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Ponderacion de <br> la Cantidad </b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Ponderacion de <br> la Oportunidad </b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Ponderacion de <br> los Indicadores <br> Cualitativos </b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Ponderacion  <br> Total </b> </h4>
                                </div>
                            </div>
                        </div>
                    </div>
                     <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="col-md-5">
                                    <div class="form-group form-md-line-input form-md-floating-label has-error">
                                        <input type="text" class="form-control" id="form_control_1">
                                        <label for="form_control_1">% Cantidad </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                    <input type="text" class="form-control" id="form_control_1">
                                    <label for="form_control_1">% Oportunidad</label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                    <input type="text" class="form-control" id="form_control_1">
                                    <label for="form_control_1">% Indicador Cualitativo </label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <div class="form-group form-md-line-input form-md-floating-label has-error">
                                    <input type="text" class="form-control" id="form_control_1">
                                    <label for="form_control_1">% Total por Operación </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-offset-5 col-md-8">
                            <br><button type="button" class="btn red">Añadir</button><br><br>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                             <table class="table table-striped table-hover" id="table_resultados">
                                <thead>
                                    <tr>
                                        <th>
                                             #
                                        </th>
                                        <th>
                                             Operacion <br>POA
                                        </th>
                                        <th>
                                             Relacion <br>con funcion<br> del Nro<br> del Puesto
                                        </th>
                                        <th>
                                             Tipo de <br>Resultado
                                        </th>
                                        <th>
                                             Medio de <br>verificacion
                                        </th>
                                        <th>
                                             Ponderacion<br> de la<br> Cantidad
                                        </th>
                                        <th>
                                             Ponderacion <br>de la<br> Oportunidad
                                        </th>
                                        <th>
                                            Ponderacion<br>de los <br>Indicadores <br>Cualitativos
                                        </th>
                                        <th>
                                             Ponderacion <br>por<br> Operacion
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>
                                             ..
                                        </td>
                                        <td>
                                             ..
                                        </td>
                                        <td>
                                             ..
                                        </td>
                                        <td >
                                             ..
                                        </td>
                                        <td>
                                           ..
                                        </td>
                                            ..
                                        <td>
                                             ..
                                        </td>
                                        <td>
                                            ..
                                        </td>
                                        <td>
                                            ..
                                        </td>
                                        <td>
                                            ..
                                        </td>
                                    </tr>
                                </tbody>
                            </table><br>
                        </div>
                    </div>
                </div>
                <div class="tab-pane " id="tab6">
                    <div class="alert alert-block alert-success fade in">
                        <button type="button" class="close" data-dismiss="alert"></button>
                        <h4 class="alert-heading">Compromiso</h4>
                        <p>
                             Cumplir como mínimo 40 horas de capacitacion durante la presente gestión.<br>
                             La suscripción del POAI supone conformidad dentro del periodo programado, con todo su contenido y compromiso de cumplimiento.
                             Por tal efecto yo, me comprometo con todo lo estipulado en el presente documento.<br><br>
                        </p>
                        <p>
                            <a class="btn green" href="javascript:;">
                            Aceptar </a>
                        </p>
                    </div>
                </div>
         
        </div>
    </div>
</div>

<link rel="stylesheet" type="text/css" href="/assets/global/plugins/select2/select2.css"/>
<script type="text/javascript" src="/assets/global/plugins/jquery-validation/js/jquery.validate.js"></script>
<script type="text/javascript" src="/assets/global/plugins/jquery-validation/js/additional-methods.min.js"></script>
<script type="text/javascript" src="/assets/global/plugins/bootstrap-wizard/jquery.bootstrap.wizard.min.js"></script>
<script type="text/javascript" src="/assets/global/plugins/select2/select2.min.js"></script>

<script>
    jQuery(document).ready(function() {
        FormWizard.init();
    });
</script>