<h3 class="page-title">
    Historial POAI's <small> </small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="/">Formulacion</a>
            <i class="fa fa-angle-right"></i>
        </li>
         <li>
            <a href="fopeReutilizarPoai">Reutilizar POAI</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Historial POAI's</a>
        </li>
    </ul>
</div>
<!-- END PAGE HEADER-->

<div class="portlet box red">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i> Historial POAI's
        </div>
        <div class="tools">
            <a href="" class="reload"></a>
        </div>
    </div>
    <div class="portlet-body form">
        <form role="form">
            <div class="form-body">

                <div class="form-group">
                                        <label class="col-md-3 control-label">Buscar Gestion:</label>
                                        <div class="col-md-3">
                                            
                                            <input type="text" class="form-control" placeholder=" ">
                                            <span class="help-block">
                                            Ejemplo: 2016 </span>
                                            
                                        </div>
                                    </div>
                </br></br></br>
                       
                                    <div class="row">
                                        <div class="col-md-offset-5 col-md-8">
                                            <button type="button" class="btn red">Buscar</button>
                                            <button type="button" class="btn red">Ver Todos</button>
                                        </div>
                            
                                </div>


                                <div class="table-scrollable">
                                <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>
                                         #
                                    </th>
                                    <th>
                                         Gestion
                                    </th>
                                    <th>
                                         Jefe Superior
                                    </th>
                                    <th>
                                         Estado
                                    </th>
                                     <th>
                                         Ver Poai
                                    </th>
                                    <th>
                                         Opciones 
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>
                                         1
                                    </td>
                                    <td>
                                         2016
                                    </td>
                                    <td>
                                        Libia Mollinedo
                                    </td>
                                    <td>
                                        <span class="label label-sm label-success">
                                        Aprobado</span>
                                    </td>
                                    <td>
                                        Ver 
                                    </td>
                                    <td>
                                        Imprimir-Exportar
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                         2
                                    </td>
                                    <td>
                                         2015
                                    </td>
                                    <td>
                                         Libia Mollinedo
                                    </td>
                                    <td>
                                         <span class="label label-sm label-danger">
                                        No Aprobado </span>
                                    </td>
                                    <td>
                                        Ver
                                    </td>
                                    <td>
                                        iMPRIMIR-eXPORTAR
                                    </td>
                                </tr>
                                </tbody>
                                </table>
                            </div>

            </div>
        </form>
    </div>
</div>
