<h3 class="page-title">
    Ver Ultimo POAI Llenado <small> </small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="/">Formulacion</a>
            <i class="fa fa-angle-right"></i>
        </li>
         <li>
            <a href="fopeReutilizarPoai">Reutilizar POAI</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Ver Ultimo POAI Llenado</a>
        </li>
    </ul>
</div>
<!-- END PAGE HEADER-->

<div class="portlet box red">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i> Ver Ultimo POAI Llenado
        </div>
        <div class="tools">
            <a href="" class="reload"></a>
        </div>
    </div>
    <div class="portlet-body form">
        <form role="form">
            <div class="form-body">
                Vista Previa:</br>
                .</br>
                .</br>
                .</br>
                .</br>
                .</br>
                .</br>
                .</br>
                .</br>
                .</br>
                .</br>
                .</br>
                .</br>
                .</br>
                .</br>
                .</br>
                .</br>
                .</br>
                .</br>
                .</br>
                .</br>
                .</br>
                .</br>
                 <div class="row">
                    <div class="col-md-offset-5 col-md-8">
                        <button type="button" class="btn red">Copiar al POAI actual</button>
                        </br></br>
                     </div>
                </div>
            </div>
        </form>
    </div>
</div>
