<h3 class="page-title">
    Prueba Formulacion <small> </small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="/">Formulacion</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Comenzar POAI</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Nro de Item</a>
        </li>
    </ul>
</div>
<div class="portlet box red">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i> Planificacion Operativa Anual Individual
        </div>
        <div class="tools">
            <a href="" class="reload"></a>
        </div>
    </div>
      <div class="portlet-body form">
        <div class="tabbable tabbable-tabdrop">
            <ul class="nav nav-tabs">
                <li class="active">
                    <a href="#tab1" data-toggle="tab">I. Identificación</a>
                </li>
                <li>
                    <a href="#tab2" data-toggle="tab">II. Descripción</a>
                </li>
                <li>
                    <a href="#tab3" data-toggle="tab">III. Especificación</a>
                </li>
                <li>
                    <a href="#tab4" data-toggle="tab">Confirmacion</a>
                </li>
                <li>
                    <a href="#tab5" data-toggle="tab">IV. Resultados Esperados</a>
                </li>

            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="tab1">

                    <div class="col-md-10" >
                        <h3 > <b> 1.1. Datos del Puesto </b> </h3>
                    </div>
                    <form class="form-inline" role="form">
                        <div class="col-md-4" >
                               Nro de Item: <label class="sr-only" ></label>
                               <label for = "nro_item" id="lab_nro_item"> &nbsp &nbsp 301 </label>
                        </div>
                        <div class="col-md-3">
                            Nivel: <label class="sr-only" ></label>
                            <label for = "nivel" id="lab_nivel"> &nbsp &nbsp 5 </label>
                        </div>
                        <div class="col-md-3">
                           Categoria: <label class="sr-only" for="exampleInputEmail2"></label>
                           <label for = " categoria" id="lab_categoria"> &nbsp &nbsp OPERATIVO </label>
                       </div>
                            </br></br></br>
                    </form>

                    <form class="form-horizontal" role="form">

                        <div class="form-group">
                            <label for="text" class="col-md-4 control-label">Denominación del cargo: </label>
                            <div class="col-md-8">
                                </br><label for = "denominacion_cargo" id="lab_denominacion_cargo"> PROFESIONAL II </label>
                            </div>
                    
                            <label for="text" class="col-md-4 control-label">Denominacion del puesto: </label>
                            <div class="col-md-8">
                                </br><label for = "denominacion_puesto" id="lab_denominacion_puesto"> RESPONSABLE DE MOVILIDAD Y REGISTRO DE PERSONAL </label>
                            </div>

                            <label for="text" class="col-md-4 control-label">Dependencia: </label>
                            <div class="col-md-8">
                                </br><label for = "dependencia" id="lab_dependencia"> UNIDAD DE RECURSOS HUMANOS</label>
                            </div>
                        </div>
                    </form>

                    <hr>

                    <div class="col-md-15" >
                        <h3> &nbsp <b> 1.2. Relaciones del Puesto </b> </h3>
                    </div> 
                    <div class="col-md-15" >
                        <h4> &nbsp &nbsp <b>1.2.1. Relaciones Jerárquicas </b></h4></br>
                    </div>


                    <div class="form-group">
                        <label for="i" class="col-md-1 control-label">Depende de: </label>
                        <div class="col-md-4">
                            <input type="text" class="form-control" id="txt_depende_de" placeholder="">
                        </div>
                        <label for="i" class="col-md-1 control-label">Supervisa a: </label>
                        <div class="col-md-4">
                            <input type="text" class="form-control" id="txt_supervisa_a_1" placeholder=""> 
                            <input type="text" class="form-control" id="txt_supervisa_a_2" placeholder="">
                            <input type="text" class="form-control" id="txt_supervisa_a_3" placeholder="">
                            <input type="text" class="form-control" id="txt_supervisa_a_4" placeholder="">
                            <input type="text" class="form-control" id="txt_supervisa_a_5" placeholder="">
                        </div>
                        <label for="i" class="col-md-1 control-label">Cantidad: </label>
                        <div class="col-md-1">
                            <input type="text" class="form-control" id="txt_cantidad_1" placeholder="">
                            <input type="text" class="form-control" id="txt_cantidad_2" placeholder="">
                            <input type="text" class="form-control" id="txt_cantidad_3" placeholder="">
                            <input type="text" class="form-control" id="txt_cantidad_4" placeholder="">
                            <input type="text" class="form-control" id="txt_cantidad_5" placeholder="">
                        </br></br></br>
                        </div>
                    </div>
                   
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> 1.2.2. Relaciones Intrainstitucionales </b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b>  1.2.3. Relaciones Interinstitucionales </b> </h4>
                                </div>
                            </div>
                        </div>
                    </div> 

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <input type="text" class="form-control" id="txt_rel_intra_1" placeholder=" 1 . ">
                                    <input type="text" class="form-control" id="txt_rel_intra_1" placeholder=" 2 . ">
                                    <input type="text" class="form-control" id="txt_rel_intra_1" placeholder=" 3 . ">
                                    <input type="text" class="form-control" id="txt_rel_intra_1" placeholder=" 4 . ">
                                    <input type="text" class="form-control" id="txt_rel_intra_1" placeholder=" 5 . ">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <input type="text" class="form-control" id="txt_rel_inter_1" placeholder=" 1 . ">
                                    <input type="text" class="form-control" id="txt_rel_intra_1" placeholder=" 2 . ">
                                    <input type="text" class="form-control" id="txt_rel_intra_1" placeholder=" 3 . ">
                                    <input type="text" class="form-control" id="txt_rel_intra_1" placeholder=" 4 . ">
                                    <input type="text" class="form-control" id="txt_rel_intra_1" placeholder=" 5 . ">
                                </br></br></br>
                                </div>
                            </div>
                        </div>
                    </div> 

                </div>
            
    
                <div class="tab-pane " id="tab2">

                    <div class="col-md-10" >
                        <h3 > <b> 2.1. Objetivo del Puesto </b> </h3>
                    </div>
                    <form class="form-horizontal" role="form">
                        <div class="form-group">
                            </br><label for="text" class="col-md-3 control-label">Qué hace? </label>
                            <div class="col-md-8">
                               <textarea rows="1" cols="90" > </textarea></br></br>
                           </div>
                        </div>
                        <div class="form-group">
                           </br><label for="text" class="col-md-3 control-label">De que forma? </label>
                           <div class="col-md-8">
                               <textarea rows="1" cols="90"> </textarea></br></br>
                           </div>
                        </div>
                        <div class="form-group">
                            </br><label for="text" class="col-md-3 control-label">Con que finalidad? </label>
                            <div class="col-md-8">
                                <textarea rows="1" cols="90"> </textarea></br></br>
                            </div>
                        </div>
                    </form>

                    <div class="col-md-10" >
                        <h3 > <b> 2.2. Normas a Cumplir </b> </h3>
                    </div >
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b> Normas Generales </b> </h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-10" >
                                    <h4 > <b>  Normas Especificas</b> </h4>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <select class="form-control input-lg">
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                    <option>Option 4</option>
                                    <option>Option 5</option>
                                </select>
                            </div>
                        </div>
                        <!--/span-->
                        <div class="col-md-6">
                            <div class="form-group">
                                <select class="form-control input-lg">
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                    <option>Option 4</option>
                                    <option>Option 5</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <select class="form-control input-lg">
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                    <option>Option 4</option>
                                    <option>Option 5</option>
                                </select>
                            </div>
                        </div>
                        <!--/span-->
                        <div class="col-md-6">
                            <div class="form-group">
                                <select class="form-control input-lg">
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                    <option>Option 4</option>
                                    <option>Option 5</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <select class="form-control input-lg">
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                    <option>Option 4</option>
                                    <option>Option 5</option>
                                </select>
                            </div>
                        </div>
                        <!--/span-->
                        <div class="col-md-6">
                            <div class="form-group">
                                <select class="form-control input-lg">
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                    <option>Option 4</option>
                                    <option>Option 5</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <select class="form-control input-lg">
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                    <option>Option 4</option>
                                    <option>Option 5</option>
                                </select>
                            </div>
                        </div>
                        <!--/span-->
                        <div class="col-md-6">
                            <div class="form-group">
                                <select class="form-control input-lg">
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                    <option>Option 4</option>
                                    <option>Option 5</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <select class="form-control input-lg">
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                    <option>Option 4</option>
                                    <option>Option 5</option>
                                </select>
                            </div>
                        </div>
                        <!--/span-->
                        <div class="col-md-6">
                            <div class="form-group">
                                <select class="form-control input-lg">
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                    <option>Option 4</option>
                                    <option>Option 5</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-10" >
                        <h3 > <b> 2.3. Funciones del Puesto </b> </h3>
                    </div>
                    <div class="col-md-10" >
                            <h4 > <b>  Funciones Generales del Puesto </b> </h4>           
                    </div>
                    <form action="#" class="horizontal-form">  
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <input type="text" class="form-control" id="txt_funciones_generales" placeholder=" 1 . ">
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <div class="radio-list">
                                                    <label class="radio-inline">
                                                        <input type="radio" name="optionsRadios" id="optionsRadios4" value="option1" checked> Recurrente </label>
                                                        <label class="radio-inline">
                                                            <input type="radio" name="optionsRadios" id="optionsRadios5" value="option2"> Producto </label>
                                                </div>
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <input type="text" class="form-control" id="txt_funciones_generales" placeholder=" 2 . ">
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <div class="radio-list">
                                                    <label class="radio-inline">
                                                        <input type="radio" name="optionsRadios" id="optionsRadios4" value="option1" checked> Recurrente </label>
                                                        <label class="radio-inline">
                                                            <input type="radio" name="optionsRadios" id="optionsRadios5" value="option2"> Producto </label>
                                                        </div>
                                                    </div>
                                                </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <input type="text" class="form-control" id="txt_funciones_generales" placeholder=" 3 . ">
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <div class="radio-list">
                                                    <label class="radio-inline">
                                                        <input type="radio" name="optionsRadios" id="optionsRadios4" value="option1" checked> Recurrente </label>
                                                        <label class="radio-inline">
                                                            <input type="radio" name="optionsRadios" id="optionsRadios5" value="option2"> Producto </label>
                                                        </div>
                                                    </div>
                                                </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <input type="text" class="form-control" id="txt_funciones_generales" placeholder=" 4 . ">
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <div class="radio-list">
                                                    <label class="radio-inline">
                                                        <input type="radio" name="optionsRadios" id="optionsRadios4" value="option1" checked> Recurrente </label>
                                                        <label class="radio-inline">
                                                            <input type="radio" name="optionsRadios" id="optionsRadios5" value="option2"> Producto </label>
                                                        </div>
                                                    </div>
                                                </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <input type="text" class="form-control" id="txt_funciones_generales" placeholder=" 5 . ">
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <div class="radio-list">
                                                    <label class="radio-inline">
                                                        <input type="radio" name="optionsRadios" id="optionsRadios4" value="option1" checked> Recurrente </label>
                                                        <label class="radio-inline">
                                                            <input type="radio" name="optionsRadios" id="optionsRadios5" value="option2"> Producto </label>
                                                        </div>
                                                    </div>
                                                </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <input type="text" class="form-control" id="txt_funciones_generales" placeholder=" 6 . ">
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <div class="radio-list">
                                                    <label class="radio-inline">
                                                    <input type="radio" name="optionsRadios" id="optionsRadios4" value="option1" checked> Recurrente </label>
                                                    <label class="radio-inline">
                                                    <input type="radio" name="optionsRadios" id="optionsRadios5" value="option2"> Producto </label>
                                                </div>
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <input type="text" class="form-control" id="txt_funciones_generales" placeholder=" 7 . ">
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <div class="radio-list">
                                                    <label class="radio-inline">
                                                    <input type="radio" name="optionsRadios" id="optionsRadios4" value="option1" checked> Recurrente </label>
                                                    <label class="radio-inline">
                                                    <input type="radio" name="optionsRadios" id="optionsRadios5" value="option2"> Producto </label>
                                                </div>
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <input type="text" class="form-control" id="txt_funciones_generales" placeholder=" 8 . ">
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <div class="radio-list">
                                                    <label class="radio-inline">
                                                        <input type="radio" name="optionsRadios" id="optionsRadios4" value="option1" checked> Recurrente </label>
                                                        <label class="radio-inline">
                                                            <input type="radio" name="optionsRadios" id="optionsRadios5" value="option2"> Producto </label>
                                                        </div>
                                                    </div>
                                                </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <input type="text" class="form-control" id="txt_funciones_generales" placeholder=" 9 . ">
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <div class="radio-list">
                                                    <label class="radio-inline">
                                                        <input type="radio" name="optionsRadios" id="optionsRadios4" value="option1" checked> Recurrente </label>
                                                        <label class="radio-inline">
                                                            <input type="radio" name="optionsRadios" id="optionsRadios5" value="option2"> Producto </label>
                                                        </div>
                                                    </div>
                                                </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <input type="text" class="form-control" id="txt_funciones_generales" placeholder=" 10 . ">
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <div class="radio-list">
                                                    <label class="radio-inline">
                                                        <input type="radio" name="optionsRadios" id="optionsRadios4" value="option1" checked> Recurrente </label>
                                                        <label class="radio-inline">
                                                            <input type="radio" name="optionsRadios" id="optionsRadios5" value="option2"> Producto </label>
                                                        </div>
                                                    </div>
                                                </div>  
                                    </div>
                                </form>         
                                <div class="col-md-10" >
                                    <h4 > <b>  Funciones Especificas del Puesto </b> </h4>
                                </div>
                                <form action="#" class="horizontal-form">  
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <input type="text" class="form-control" id="txt_funciones_generales" placeholder=" 1 . ">
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <div class="radio-list">
                                                    <label class="radio-inline">
                                                    <input type="radio" name="optionsRadios" id="optionsRadios4" value="option1" checked> Recurrente </label>
                                                    <label class="radio-inline">
                                                    <input type="radio" name="optionsRadios" id="optionsRadios5" value="option2"> Producto </label>
                                                </div>
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <input type="text" class="form-control" id="txt_funciones_generales" placeholder=" 2 . ">
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <div class="radio-list">
                                                    <label class="radio-inline">
                                                    <input type="radio" name="optionsRadios" id="optionsRadios4" value="option1" checked> Recurrente </label>
                                                    <label class="radio-inline">
                                                    <input type="radio" name="optionsRadios" id="optionsRadios5" value="option2"> Producto </label>
                                                </div>
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <input type="text" class="form-control" id="txt_funciones_generales" placeholder=" 3 . ">
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <div class="radio-list">
                                                    <label class="radio-inline">
                                                    <input type="radio" name="optionsRadios" id="optionsRadios4" value="option1" checked> Recurrente </label>
                                                    <label class="radio-inline">
                                                    <input type="radio" name="optionsRadios" id="optionsRadios5" value="option2"> Producto </label>
                                                </div>
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <input type="text" class="form-control" id="txt_funciones_generales" placeholder=" 4 . ">
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <div class="radio-list">
                                                    <label class="radio-inline">
                                                    <input type="radio" name="optionsRadios" id="optionsRadios4" value="option1" checked> Recurrente </label>
                                                    <label class="radio-inline">
                                                        <input type="radio" name="optionsRadios" id="optionsRadios5" value="option2"> Producto </label>
                                                </div>
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <input type="text" class="form-control" id="txt_funciones_generales" placeholder=" 5 . ">
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <div class="radio-list">
                                                    <label class="radio-inline">
                                                        <input type="radio" name="optionsRadios" id="optionsRadios4" value="option1" checked> Recurrente </label>
                                                        <label class="radio-inline">
                                                            <input type="radio" name="optionsRadios" id="optionsRadios5" value="option2"> Producto </label>
                                                        </div>
                                                    </div>
                                                </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <input type="text" class="form-control" id="txt_funciones_generales" placeholder=" 6 . ">
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <div class="radio-list">
                                                    <label class="radio-inline">
                                                        <input type="radio" name="optionsRadios" id="optionsRadios4" value="option1" checked> Recurrente </label>
                                                        <label class="radio-inline">
                                                            <input type="radio" name="optionsRadios" id="optionsRadios5" value="option2"> Producto </label>
                                                </div>
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <input type="text" class="form-control" id="txt_funciones_generales" placeholder=" 7 . ">
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <div class="radio-list">
                                                    <label class="radio-inline">
                                                        <input type="radio" name="optionsRadios" id="optionsRadios4" value="option1" checked> Recurrente </label>
                                                        <label class="radio-inline">
                                                            <input type="radio" name="optionsRadios" id="optionsRadios5" value="option2"> Producto </label>
                                                </div>
                                            </div>
                                        </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <input type="text" class="form-control" id="txt_funciones_generales" placeholder=" 8 . ">
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <div class="radio-list">
                                                    <label class="radio-inline">
                                                        <input type="radio" name="optionsRadios" id="optionsRadios4" value="option1" checked> Recurrente </label>
                                                        <label class="radio-inline">
                                                            <input type="radio" name="optionsRadios" id="optionsRadios5" value="option2"> Producto </label>
                                                        </div>
                                                    </div>
                                                </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <input type="text" class="form-control" id="txt_funciones_generales" placeholder=" 9 . ">
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <div class="radio-list">
                                                    <label class="radio-inline">
                                                        <input type="radio" name="optionsRadios" id="optionsRadios4" value="option1" checked> Recurrente </label>
                                                        <label class="radio-inline">
                                                            <input type="radio" name="optionsRadios" id="optionsRadios5" value="option2"> Producto </label>
                                                        </div>
                                                    </div>
                                                </div>  
                                    </div>
                                    <div class="row">              
                                        <div class="col-md-6">                    
                                            <input type="text" class="form-control" id="txt_funciones_generales" placeholder=" 10 . ">
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <div class="radio-list">
                                                    <label class="radio-inline">
                                                        <input type="radio" name="optionsRadios" id="optionsRadios4" value="option1" checked> Recurrente </label>
                                                        <label class="radio-inline">
                                                            <input type="radio" name="optionsRadios" id="optionsRadios5" value="option2"> Producto </label>
                                                        </div>
                                                    </div>
                                                </div>  
                                    </div>

                                </form>
                </div>
     
                <div class="tab-pane " id="tab3">

                    3
                </div>
      
                <div class="tab-pane " id="tab4">

                    4
                </div>
      
                <div class="tab-pane " id="tab5">

                    5
                </div>
   
        </div>
    </div>
</div>

<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="../../assets/global/plugins/respond.min.js"></script>
<script src="../../assets/global/plugins/excanvas.min.js"></script> 
<![endif]-->
<script src="../../assets/global/plugins/jquery.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
<!-- IMPORTANT! Load jquery-ui.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<script src="../../assets/global/plugins/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="../../assets/global/plugins/bootstrap-tabdrop/js/bootstrap-tabdrop.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="../../assets/global/scripts/metronic.js" type="text/javascript"></script>
<script src="../../assets/admin/layout/scripts/layout.js" type="text/javascript"></script>
<script src="../../assets/admin/layout/scripts/quick-sidebar.js" type="text/javascript"></script>
<script src="../../assets/admin/layout/scripts/demo.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script>
jQuery(document).ready(function() {       
   // initiate layout and plugins
   Metronic.init(); // init metronic core components
Layout.init(); // init current layout
QuickSidebar.init(); // init quick sidebar
Demo.init(); // init demo features
});
</script>
<!-- END JAVASCRIPTS -->