<h3 class="page-title">
    Historial Gestiones  <small> </small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="/">Formulacion</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="fsaGestion">Gestión</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Historial Gestiones</a>
        </li>
    </ul>
</div>
<!-- END PAGE HEADER-->

<div class="portlet box red">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa fa-gift"></i> Historial Gestión / Versión
                            </div>
                            <div class="tools">
                                <a href="" class="reload">
                                </a>
                    
                            </div>
                        </div>
                        <div class="portlet-body form">
                            <form role="form">
                                <div class="form-body">
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Unidad</label>
                                        <div class="col-md-5">
                                            <select class="form-control">
                                                <option>Unidad de Tecnologias de Informacion</option>
                                                <option>Unidad de Recursos Humanos</option>
                                                <option>Unidad Financiera</option>
                                            </select>
                                        </div>
                                    </div>
                                    </br></br>
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Buscar Gestion:</label>
                                        <div class="col-md-3">
                                            
                                            <input type="text" class="form-control" placeholder=" ">
                                            <span class="help-block">
                                            Ejemplo: 2016 </span>
                                            
                                        </div>
                                    </div>
                                </div>

                            </br></br></br>
                               
                                    <div class="row">
                                        <div class="col-md-offset-5 col-md-8">
                                            <button type="button" class="btn red">Buscar</button>
                                            <button type="button" class="btn red">Ver Todos</button>
                                              </br>  </br>
                                        </div>
                         
                                </div>



                    <div class="portlet-body">
                            <div class="table-scrollable">
                                <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>
                                         #
                                    </th>
                                    <th>
                                         Gestion
                                    </th>
                                    <th>
                                         Fecha de Cambios
                                    </th>
                                    <th>
                                         Motivos
                                    </th>
                                    <th>
                                         Estado
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>
                                         1
                                    </td>
                                    <td>
                                         2016
                                    </td>
                                    <td>
                                         00/00/0000
                                    </td>
                                    <td>
                                         Creacion de Gestion
                                    </td>
                                    <td>
                                        <span class="label label-sm label-success">
                                        Vigente</span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                         2
                                    </td>
                                    <td>
                                         2015
                                    </td>
                                    <td>
                                         00/00/0000
                                    </td>
                                    <td>
                                         Dar de baja
                                    </td>
                                    <td>
                                        <span class="label label-sm label-danger">
                                        No Vigente </span>
                                    </td>
                                </tr>
                                </tbody>
                                </table>
                            </div>
                        </div>
                        <br>
                        </form>
                        </div>
                    </div>