<h3 class="page-title">
    Dar de Alta/Baja Usuarios  <small> </small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="/">Formulacion</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="fsaHabilitarUsuarios">Habilitar Usuarios</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Dar de ALta/Baja Usuarios</a>
        </li>
    </ul>
</div>
<!-- END PAGE HEADER-->

<div class="portlet box red">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa fa-gift"></i> Historial Gestión / Versión
                            </div>
                            <div class="tools">
                                <a href="" class="reload">
                                </a>
                    
                            </div>
                        </div>
                        <div class="portlet-body form">
                            <form role="form">
                                <div class="form-body">
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Unidad</label>
                                        <div class="col-md-5">
                                            <select class="form-control">
                                                <option>Unidad de Tecnologias de Informacion</option>
                                                <option>Unidad de Recursos Humanos</option>
                                                <option>Unidad Financiera</option>
                                            </select>
                                        </div>
                                    </div>
                                    </br></br>
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Buscar por Item:</label>
                                        <div class="col-md-3">
                                            
                                            <input type="text" class="form-control" placeholder=" ">
                                            <span class="help-block">
                                            Ejemplo: 343 </span>
                                        </div>
                                    </div>
                                </div>

                            </br></br></br>
                                <div class="form-actions ">
                                    <div class="row">
                                        <div class="col-md-offset-5 col-md-8">
                                            <button type="button" class="btn red">Buscar</button>
                                    
                                        </div>
                                    </div>
                                </div>



<div class="portlet-body">
                            <div class="table-scrollable">
                                <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>
                                         #
                                    </th>
                                    <th>
                                         Item
                                    </th>
                                    <th>
                                         Nombre Completo
                                    </th>
                                    <th>
                                         Unidad
                                    </th>
                                    <th>
                                         Rol en el Sistema
                                    </th>
                                    <th>
                                         Estado
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>
                                         1
                                    </td>
                                    <td>
                                         343
                                    </td>
                                    <td>
                                         Andrea Moscoso
                                    </td>
                                    <td>
                                         Unidad de Recursos Humanos
                                    </td>
                                    <td>
                                        Administrador
                                    </td>
                                    <td>
                                        vigente / no vigente
                                    </td>
                                </tr>
                    
                                </tbody>
                                </table>
                            </div>
                        </div>


                        </br></br></br>
                                <div class="form-actions ">
                                    <div class="row">
                                        <div class="col-md-offset-5 col-md-8">
                                            <button type="button" class="btn red">Guardar</button>
                                            <button type="button" class="btn red">Cancelar</button>
                                        </div>
                                    </div>
                                </div>


                        <br>
                        </form>
                        </div>
                    </div>