<h3 class="page-title">
    Pagina de Inicio  <small> </small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="/">Principal</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="inicio">Página de Inicio</a>
        </li>
    </ul>
</div>
<!-- END PAGE HEADER-->

<div class="row">
    
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12" >
        <div class="dashboard-stat red-intense">
            <div class="visual">
                
                <i class="fa fa-globe"></i>
            </div>
            <div class="details">
                <div class="number">
                    FORMULACION
                </div>
            </div>
            <a class="more" href="fsaCrearGestiones">
                View more <i class="m-icon-swapright m-icon-white"></i>
                 </a>
            </a>
        </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
        <div class="dashboard-stat green-haze">
            <div class="visual">
                <i class="fa fa-shopping-cart"></i>
            </div>
            <div class="details">
                <div class="number">
                    SEGUIMIENTO
                </div>
            </div>
            <a class="more" href="sadmControlAvance">
                View more <i class="m-icon-swapright m-icon-white"></i>
            </a>
        </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
        <div class="dashboard-stat purple-plum">
            <div class="visual">
                <i class="fa fa-bar-chart-o"></i>
            </div>
            <div class="details">
                <div class="number">
                    EVALUACION
                </div>
            </div>
            <a class="more" href="eadmControlAvance2">
                View more <i class="m-icon-swapright m-icon-white"></i>
            </a>
        </div>
    </div>
</div>

<div class="clearfix">
</div>



                    <div class="portlet light bg-inverse">
                        <div class="portlet-title">
                            <div class="caption font-red-intense">
                                <i class="icon-speech font-red-intense"></i>
                                <span class="caption-subject bold uppercase"> FORMULACION</span>
                                <span class="caption-helper"></span>
                            </div>
                            <div class="tools">
                                <a href="" class="collapse" data-original-title="" title="">
                                </a>
                                <a href="" class="reload" data-original-title="" title="">
                                </a>
                                <a href="" class="fullscreen" data-original-title="" title="">
                                </a>                        
                            </div>
                        </div>
                        <div class="portlet-body">
                            <div id="context2" data-toggle="context" data-target="#context-menu">
                                <p>
                                    Se especifica la funcion de cada puesto....
                                </p>
                            </div>
                            <!-- Your custom menu with dropdown-menu as default styling -->
                            <div id="context-menu">
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="javascript:;">
                                        <i class="icon-user"></i> New User </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <i class="icon-present"></i> New Event <span class="badge badge-success">4</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <i class="icon-basket"></i> New order </a>
                                    </li>
                                    <li class="divider">
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <i class="icon-flag"></i> Pending Orders <span class="badge badge-danger">4</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <i class="icon-users"></i> Pending Users <span class="badge badge-warning">12</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="portlet light bg-inverse">
                        <div class="portlet-title">
                            <div class="caption font-green-haze">
                                <i class="icon-speech font-green-haze"></i>
                                <span class="caption-subject bold uppercase"> SEGUIMIENTO</span>
                                <span class="caption-helper"></span>
                            </div>
                             <div class="tools">
                                <a href="" class="collapse" data-original-title="" title="">
                                </a>
                                <a href="" class="reload" data-original-title="" title="">
                                </a>
                                <a href="" class="fullscreen" data-original-title="" title="">
                                </a>                        
                            </div>
                        </div>
                        <div class="portlet-body">
                            <div id="context2" data-toggle="context" data-target="#context-menu">
                                <p>
                                     Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit.
                                </p>
                            </div>
                            <!-- Your custom menu with dropdown-menu as default styling -->
                            <div id="context-menu">
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="javascript:;">
                                        <i class="icon-user"></i> New User </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <i class="icon-present"></i> New Event <span class="badge badge-success">4</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <i class="icon-basket"></i> New order </a>
                                    </li>
                                    <li class="divider">
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <i class="icon-flag"></i> Pending Orders <span class="badge badge-danger">4</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <i class="icon-users"></i> Pending Users <span class="badge badge-warning">12</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="portlet light bg-inverse">
                        <div class="portlet-title">
                            <div class="caption font-purple-plum">
                                <i class="icon-speech font-purple-plum"></i>
                                <span class="caption-subject bold uppercase">EVALUACION</span>
                                <span class="caption-helper"></span>
                            </div>
                             <div class="tools">
                                <a href="" class="collapse" data-original-title="" title="">
                                </a>
                                <a href="" class="reload" data-original-title="" title="">
                                </a>
                                <a href="" class="fullscreen" data-original-title="" title="">
                                </a>                        
                            </div>
                        </div>
                        <div class="portlet-body">
                            <div id="context2" data-toggle="context" data-target="#context-menu">
                                <p>
                                     Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit.
                                </p>
                            </div>
                            <!-- Your custom menu with dropdown-menu as default styling -->
                            <div id="context-menu">
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="javascript:;">
                                        <i class="icon-user"></i> New User </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <i class="icon-present"></i> New Event <span class="badge badge-success">4</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <i class="icon-basket"></i> New order </a>
                                    </li>
                                    <li class="divider">
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <i class="icon-flag"></i> Pending Orders <span class="badge badge-danger">4</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                        <i class="icon-users"></i> Pending Users <span class="badge badge-warning">12</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>