<h3 class="page-title">
    Historial de Asignaciones  <small> </small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="/">Seguimiento</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Historial de Asignaciones</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Historial de Asignaciones</a>
        </li>
    </ul>
</div>
<!-- END PAGE HEADER-->
<div class="portlet box green">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa fa-gift"></i> Historial Gestión / Versión
                            </div>
                            <div class="tools">
                                <a href="" class="reload">
                                </a>
                    
                            </div>
                        </div>
                        <div class="portlet-body form">
                            <form role="form">
                                <div class="form-body">
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Unidad</label>
                                        <div class="col-md-5">
                                            <select class="form-control">
                                                <option>Unidad de Tecnologias de Informacion</option>
                                                <option>Unidad de Recursos Humanos</option>
                                                <option>Unidad Financiera</option>
                                            </select>
                                        </div>
                                    </div>
                          
                                </div>

                            </br>
                    
                                    <div class="row">
                                        <div class="col-md-offset-5 col-md-8">
                                            <button type="button" class="btn green">Buscar</button>
                                            <button type="button" class="btn green">Ver Todos</button>
                                        </div>
                           
                                </div>



                    <div class="portlet-body">
                            <div class="table-scrollable">
                                <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>
                                         Unidad 
                                    </th>
                                    <th>
                                        Responsable
                                   </th>
                                    <th>
                                         Fecha de Asignacion 
                                    </th>
                                    <th>
                                         Fecha Finalizacion
                                    </th>
                                
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>
                                         1
                                    </td>
                                    <td>
                                         Unidad de Recursos Humanos
                                    </td>
                                    <td>
                                        Andrea Moscoso
                                    </td>
                                    <td>
                                         12/02/2016
                                    </td>
                                
                                </tr>
                                <tr>
                                    <td>
                                         2
                                    </td>
                                    <td>
                                         Unidaded de Tecnologias de la Informacion 
                                    </td>
                                    <td>
                                         Jorge Uriarte
                                    </td>
                                    <td>
                                         12/02/2016
                                    </td>
                                 
                                </tr>
                                </tbody>
                                </table>
                            </div>
                        </div>
                        <br>
                        </form>
                        </div>
                    </div>