<h3 class="page-title">
    Registro de Acontecimientos  <small> </small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="/">Seguimiento</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Control de Seguimiento</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Registro de Acontecimientos</a>
        </li>
    </ul>
</div>
<!-- END PAGE HEADER-->
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-tasks"></i> Registro de Acontecimientoss
        </div>
        <div class="tools">
            <a href="" class="reload"></a>
        </div>
    </div>
    <div class="portlet-body form">
        <div class="tabbable tabbable-tabdrop">
                                <ul class="nav nav-tabs">
                                    <li class="active">
                                        <a href="#tab1" data-toggle="tab">Parte 1</a>
                                    </li>
                                    <li>
                                        <a href="#tab2" data-toggle="tab">Parte 2</a>
                                    </li>
                                    <li>
                                        <a href="#tab3" data-toggle="tab">Parte 3</a>
                                    </li>
                                   
                                
                                </ul>
                                <div class="tab-content">
                                    <div class="tab-pane active" id="tab1">
                                        <h3 class="col-md-5">Datos del Servidor Publico</h3>
                                        <br><br><br>
                            <form class="form-horizontal" role="form">
                                <div class="form-group">
                                    <label for="inputEmail1" class="col-md-4 control-label">Apellidos y Nombres del Servidor Publico </label>
                                    <div class="col-md-5">
                                        <input type="email" class="form-control" id="inputEmail1" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Puesto que ocupa: </label>
                                    <div class="col-md-5">
                                        <input type="password" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                 <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Cargo que ocupa: </label>
                                    <div class="col-md-5">
                                        <input type="password" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Area Organizacional: </label>
                                    <div class="col-md-5">
                                        <input type="password" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Jefe Inmediato Superior: </label>
                                    <div class="col-md-5">
                                        <input type="password" class="form-control" id="inputPassword12" placeholder="Nombre y Apellidos Completos">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Puesto del Jefe Inmediatos Superior: </label>
                                    <div class="col-md-5">
                                        <input type="password" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                <div class="row">
                                        <div class="col-md-offset-10 col-md-8">
                                            <button type="button" class="btn green">Guardar </button>
                                        </div>
                                    </br></br>
                                </div>

                            </form>
                            
                         

                                    </div>
                                    <div class="tab-pane" id="tab2">
                                                <h3  class="col-md-10" >Detalle de Acontecimientos Notables Positivos</h3>
                                       <form class="form-horizontal" role="form">
                                <div class="form-group">
                                    <label for="inputEmail1" class="col-md-4 control-label">Fecha: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputEmail1" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Acontecimiento Notable Positivo: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                 <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Comportamiento observado: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                
                                <div class="row">
                                        <div class="col-md-offset-5 col-md-8">
                                            <button type="button" class="btn green">Añadir </button>
                                             <button type="button" class="btn green">Nuevo </button>
                                        </div>
                                    </br></br>
                                </div>


                                <div class="table-scrollable">
                                <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>
                                         #
                                    </th>
                                    <th>
                                         Fecha
                                    </th>
                                    <th>
                                         Acontecimiento Notable Positivo 
                                    </th>
                                    <th>
                                         Comportamiento Observado
                                    </th>
                                    
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>
                                         1
                                    </td>
                                    <td>
                                        02/02/2016
                                    </td>
                                    <td>
                                        1
                                    </td>
                                    <td>
                                        Elaboracion de la Especificaciones Tecnicas de Sistema Integral de Seguridad del Edificio del MEFP.
                                    </td>
                                    <td>
                                       Proactivo
                                    </td>
                                   
                                </tr>
                                
                                </tbody>
                                </table>
                            </div>
                            <div class="row">
                                        <div class="col-md-offset-10 col-md-8">
                                            <button type="button" class="btn green">Guardar </button>
                                        </div>
                                    </br></br>
                                </div>
                            </form>

                                    </div>
                                    <div class="tab-pane" id="tab3">
                                        <h3  class="col-md-10" >Detalle de Acontecimientos Notables Negativos</h3>
                                        <form class="form-horizontal" role="form">
                                <div class="form-group">
                                    <label for="inputEmail1" class="col-md-4 control-label">Numero de Resultado: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputEmail1" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Descripcion del Resultado: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Descripcion del Resultado Alcanzado: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputtext" placeholder="En terminos de cantidad, oportunidad, fecha de Inicio y finalizacion">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Medios de Verificacion: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Recursos Asignados: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Comentarios: </label>
                                    <div class="col-md-5">
                                        <input type="text "class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                <div class="row">
                                        <div class="col-md-offset-5 col-md-8">
                                            <button type="button" class="btn green">Añadir </button>
                                             <button type="button" class="btn green">Nuevo </button>
                                        </div>
                                    </br></br>
                                </div>


                                <div class="table-scrollable">
                                <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>
                                         Nro de <br> Resultado
                                    </th>
                                    <th>
                                         Descripcion del <br> Resultado
                                    </th>
                                    <th>
                                         Descripcion del resultado alcanzado <br> en terminos de cantidad, oportunidad,<br> fecha de inicio y finalizacion 
                                    </th>
                                    <th>
                                        Medio de <br> Verificacion
                                    </th>
                                    <th>
                                        Recursos <br> Asignados
                                    </th>   
                                    <th>
                                        Comentarios
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>
                                         1
                                    </td>
                                    <td>
                                         Elaboracion de las especificaciones tecnicas para el sistema un integrado de seguridad...
                                    </td>
                                    <td>
                                        Adjudicacion dek lote N2 del DBC (Equipo Electronico Ultrasonico, Arcos detectores de metales y explosivos, escaner RX...)
                                    </td>
                                    <td>
                                        Contrato Administrativo
                                    </td>
                                    <td>
                                       SI
                                    </td>
                                    <td>
                                        Sin comentarios
                                    </td>   
                                </tr>
                                
                                </tbody>
                                </table>
                            </div>
                            <div class="row">
                                        <div class="col-md-offset-10 col-md-8">
                                            <button type="button" class="btn green">Guardar </button>
                                        </div>
                                    </br></br>
                                </div>
                            </form>
                                    </div>
                                    
                                    </div>
                                </div>
                            </div>
    </div>
    </div>
</div>