<h3 class="page-title">
    Control de Avance  <small> </small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="/">Seguimiento</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Control de Seguimiento</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Control de Avance</a>
        </li>
    </ul>
</div>
<!-- END PAGE HEADER-->
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-tasks"></i> Control de Avance 
        </div>
        <div class="tools">
            <a href="" class="reload"></a>
        </div>
    </div>
    <div class="portlet-body form">
        <form role="form">
            <div class="form-body">
                <div class="form-group">
                                        
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Buscar Gestion:</label>
                                        <div class="col-md-3">
                                            
                                            <input type="text" class="form-control" placeholder=" ">
                                            <span class="help-block">
                                            Ejemplo: 2016 </span>
                                            
                                        </div>
                                    </div>
                                    </br></br></br>
                   
                                    <div class="row">
                                        <div class="col-md-offset-5 col-md-8">
                                            <button type="button" class="btn green">Buscar</button>
                                            <button type="button" class="btn green">Ver Todos</button>
                                            
                                        </div>
                                    </br></br>
                                </div>
                                <div class="table-scrollable">
                                <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>
                                         #
                                    </th>
                                    <th>
                                         Item
                                    </th>
                                    <th>
                                         Ver
                                    </th>
                                    <th>
                                         Estado
                                    </th>
                                    <th>
                                         Control de Seguimiento
                                    </th>

                                    <th>
                                         Opciones
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>
                                         1
                                    </td>
                                    <td>
                                         301
                                    </td>
                                    <td>
                                        Ver <i class="fa fa-file-archive-o"></i>
                                    </td>
                                    <td>
                                         <span class="label label-sm label-success">
                                        Finalizado</span>
                                    </td>
                                    <td>
                                         <div class="progress">
                                            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                                                <span class="sr-only">
                                                100% Complete </span>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        Imprimir <i class="fa fa-print"></i>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                         2
                                    </td>
                                    <td>
                                         302
                                    </td>
                                     <td>
                                        Ver <i class="fa fa-file-archive-o"></i>
                                    </td>
                                    <td>
                                         <span class="label label-sm label-danger">
                                        Por llenar </span>
                                    </td>
                                    <td>
                                         <div class="progress">
                                            <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 2%">
                                                <span class="sr-only">
                                              2% Complete </span>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        Imprimir <i class="fa fa-print"></i>
                                    </td>
                                </tr>
                                </tbody>
                                </table>
                            </div>
            </div>
        </form>
    </div>
</div>