<h3 class="page-title">
    Busqueda de Actividades  <small> </small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="/">Seguimiento</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Busqueda de Actividades</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Busqueda de Actividades</a>
        </li>
    </ul>
</div>

<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-tasks"></i> Busqueda de Actividades  
        </div>
        <div class="tools">
            <a href="" class="reload"></a>
        </div>
    </div>
    <div class="portlet-body form">
        <form role="form">
            <div class="form-body">
            <div class="row">
                
                 
                <div class="form-group">
                    <label class="col-md-2 control-label">Actividad</label>
                        <div class="col-md-6">
                            <select class="form-control">
                                <option>Cumplimiento de las resultados especificados en el POAI</option>
                                <option>Realizacion...</option>
                            </select>
                             </br>
                        </div>

                </div>
                 <div class="form-group">
                    <label class="col-md-1 control-label">Nro Item</label>
                        <div class="col-md-2">
                            <select class="form-control">
                                <option>301</option>
                                <option>302</option>
                                <option>303</option>
                            </select>
                        </div>
                         </br> </br>
                </div>
                 <div class="form-group">
                    <label class="col-md-2 control-label">Nro de Resultado</label>
                        <div class="col-md-2">
                            <input type="text" class="form-control" placeholder=" ">
                        </div>
                </div>
                 <div class="form-group">
                    <label class="col-md-3 control-label">Descripcion del resultado </label>
                        <div class="col-md-5">
                            <input type="text" class="form-control" placeholder=" " >
                        </div>
                </div>
            </br></br>                
                                    <div class="row">
                                        <div class="col-md-offset-5 col-md-8">
                                            <button type="button" class="btn green">Buscar</button> 
                                            <div class="col-md-offset-5 col-md-8">
                                        Opciones de Reporte : <i class="fa fa-file-pdf-o"></i> Imprimir: <i class="fa fa-print"></i>
                                    </div>
                                        </div>

                                    </div>

                                </div>
                                <div class="portlet-body">
                            <div class="table-scrollable">
                                <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>
                                         Nro </br> Resultado
                                    </th>
                                    <th>
                                         Descripcion </br> del </br> Resultado
                                    </th>
                                    <th>
                                         Cantidad </br> Realizada 
                                    </th>
                                    <th>
                                         Oportunidad </br> Alcanzada
                                    </th>
                                    <th>
                                         Indicadores </br> Cualitativos </br> Alcanzados 
                                    </th>
                                    <th>
                                        Medio </br> de </br>  Verificacion 
                                    </th>
                                    <th>
                                        Recursos </br> Asignados 
                                    </th>
                                    <th>
                                        Comentarios
                                    </th>   
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>
                                         1
                                    </td>
                                    <td>
                                         .....
                                    </td>
                                    <td>
                                         .....
                                    </td>
                                    <td>
                                         .....
                                    </td>
                                    <td>
                                       ......
                                    </td>
                                    <td>
                                        ......
                                    </td>
                                    <td>
                                        ......
                                    </td>
                                    <td>
                                        .....
                                    </td>
                                    
                                </tr>
                                </tbody>
                                </table>
                            </div>
                        </div>
     
            </div>
        </form>
    </div>
</div>
