<h3 class="page-title">
    Historial - Cambios  <small> </small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="/">Seguimiento</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>

            <a href="#">Historial - Cambios</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Historial - Cambios</a>
        </li>
    </ul>
</div>

<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-tasks"></i> Historial Cambios
        </div>
        <div class="tools">
            <a href="" class="reload"></a>
        </div>
    </div>
    <div class="portlet-body form">
                            <form role="form">
                                <div class="form-body">
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Buscar en el Historial: </label>
                                        <div class="col-md-5">
                                            <input type="text" class="form-control" placeholder=" ">
                                        </div>
                                    </div>
                          
                                </div>

                            </br>
                    
                                    <div class="row">
                                        <div class="col-md-offset-5 col-md-8">
                                            <button type="button" class="btn green">Buscar</button>
                                            <button type="button" class="btn green">Ver Todos</button>
                                        </div>
                           
                                </div>



                    <div class="portlet-body">
                            <div class="table-scrollable">
                                <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>
                                         Nro 
                                    </th>
                                    <th>
                                        Fecha - Hora
                                   </th>
                                    <th>
                                         Historial
                                    </th>
                                    <th>
                                         Cambios realizados
                                    </th>
                                
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>
                                         01
                                    </td>
                                    <td>
                                         10/03/2015 8:53:00
                                    </td>
                                    <td>
                                        Cumplimiento de los resultados....
                                    </td>
                                    <td>
                                         Modificado
                                    </td>
                                
                                </tr>
                                <tr>
                                    <td>
                                         02
                                    </td>
                                    <td>
                                         10/03/2015 10:53:00 
                                    </td>
                                    <td>
                                         Datos del servidor publico 
                                    </td>
                                    <td>
                                         Vista
                                    </td>
                                 
                                </tr>
                                 <tr>
                                    <td>
                                         03
                                    </td>
                                    <td>
                                         11/03/2015 15:23:00 
                                    </td>
                                    <td>
                                         Necesidad de Capacitacion 
                                    </td>
                                    <td>
                                         Vista
                                    </td>
                                 
                                </tr>
                                </tbody>
                                </table>
                            </div>
                        </div>
                        <br>
                        </form>
                        </div>
</div>