<h3 class="page-title">
    Registro de Actividades  <small> </small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="/">Seguimiento</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Control de Avance</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Registro de Actividades</a>
        </li>
    </ul>
</div>
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-tasks"></i> Registro de Actividades
        </div>
        <div class="tools">
            <a href="" class="reload"></a>
        </div>
    </div>
    <div class="portlet-body form">
        <div class="tabbable tabbable-tabdrop">
                                <ul class="nav nav-tabs">
                                    <li class="active">
                                        <a href="#tab1" data-toggle="tab">Parte 1</a>
                                    </li>
                                    <li>
                                        <a href="#tab2" data-toggle="tab">Parte 2</a>
                                    </li>
                                    <li>
                                        <a href="#tab3" data-toggle="tab">Parte 3</a>
                                    </li>
                                    <li>
                                        <a href="#tab4" data-toggle="tab">Parte 4</a>
                                    </li>
                                    <li>
                                        <a href="#tab5" data-toggle="tab">Parte 5</a>
                                    </li>
                                    <li>
                                        <a href="#tab6" data-toggle="tab">Parte 6</a>
                                    </li>
                                
                                </ul>
                                <div class="tab-content">
                                    <div class="tab-pane active" id="tab1">
                                        <h3 class="col-md-5">Datos del Servidor Publico</h3>
                                        <br><br><br>
                            <form class="form-horizontal" role="form">
                                <div class="form-group">
                                    <label for="inputEmail1" class="col-md-4 control-label">Apellidos y Nombres del Servidor Publico </label>
                                    <div class="col-md-5">
                                        <input type="email" class="form-control" id="inputEmail1" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Puesto que ocupa: </label>
                                    <div class="col-md-5">
                                        <input type="password" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                 <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Cargo que ocupa: </label>
                                    <div class="col-md-5">
                                        <input type="password" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Area Organizacional: </label>
                                    <div class="col-md-5">
                                        <input type="password" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Jefe Inmediato Superior: </label>
                                    <div class="col-md-5">
                                        <input type="password" class="form-control" id="inputPassword12" placeholder="Nombre y Apellidos Completos">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Puesto del Jefe Inmediatos Superior: </label>
                                    <div class="col-md-5">
                                        <input type="password" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                <div class="row">
                                        <div class="col-md-offset-10 col-md-8">
                                            <button type="button" class="btn green">Guardar </button>
                                        </div>
                                    </br></br>
                                </div>

                            </form>
                            
                         

                                    </div>
                                    <div class="tab-pane" id="tab2">
                                                <h3  class="col-md-10" >Cumplimiento de los Resultados Establecidos en el POAI</h3>
                                       <form class="form-horizontal" role="form">
                                <div class="form-group">
                                    <label for="inputEmail1" class="col-md-4 control-label">Descripcion del Resultado: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputEmail1" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Cantidad Realizada: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                 <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Oportunidad Alcanzada: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Indicador Cualitativo Alcanzado: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Medios de Verificacion: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputPassword12" placeholder="Nombre y Apellidos Completos">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Recursos Asignados: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Comentarios: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                <div class="row">
                                        <div class="col-md-offset-5 col-md-8">
                                            <button type="button" class="btn green">Añadir </button>
                                             <button type="button" class="btn green">Nuevo </button>
                                        </div>
                                    </br></br>
                                </div>


                                <div class="table-scrollable">
                                <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>
                                         Nro de <br> Resultado
                                    </th>
                                    <th>
                                         Descripcion del Resultado
                                    </th>
                                    <th>
                                         Cantidad <br> Realizada 
                                    </th>
                                    <th>
                                         Oportunidad Alcanzada
                                    </th>
                                    <th>
                                         Indicadores <br> Cualitativos <br>Alcanzados 
                                    </th>
                                    <th>
                                        Medio de Verificacion
                                    </th>
                                    <th>
                                        Recursos <br> Asignados
                                    </th>   
                                    <th>
                                        Comentarios
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>
                                         1
                                    </td>
                                    <td>
                                         Gestionar las tecnologias de informacion y comunicacion del MEFP....
                                    </td>
                                    <td>
                                        1
                                    </td>
                                    <td>
                                        Se cumplio con los trabajos programados en la gestion.
                                    </td>
                                    <td>
                                       100%
                                    </td>
                                    <td>
                                        Informes trimestrales de las areas
                                    </td>   
                                    <td>
                                        SI
                                    </td>
                                    <td>
                                        Sin comemtarios
                                    </td>   
                                </tr>
                                
                                </tbody>
                                </table>
                            </div>
                            <div class="row">
                                        <div class="col-md-offset-10 col-md-8">
                                            <button type="button" class="btn green">Guardar </button>
                                        </div>
                                    </br></br>
                                </div>
                            </form>

                                    </div>
                                    <div class="tab-pane" id="tab3">
                                        <h3  class="col-md-10" >Resultados Asignados en la Gestion no Especificados en el POAI</h3>
                                        <form class="form-horizontal" role="form">
                                <div class="form-group">
                                    <label for="inputEmail1" class="col-md-4 control-label">Numero de Resultado: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputEmail1" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Descripcion del Resultado: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Descripcion del Resultado Alcanzado: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputtext" placeholder="En terminos de cantidad, oportunidad, fecha de Inicio y finalizacion">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Medios de Verificacion: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Recursos Asignados: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Comentarios: </label>
                                    <div class="col-md-5">
                                        <input type="text "class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                <div class="row">
                                        <div class="col-md-offset-5 col-md-8">
                                            <button type="button" class="btn green">Añadir </button>
                                             <button type="button" class="btn green">Nuevo </button>
                                        </div>
                                    </br></br>
                                </div>


                                <div class="table-scrollable">
                                <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>
                                         Nro de <br> Resultado
                                    </th>
                                    <th>
                                         Descripcion del <br> Resultado
                                    </th>
                                    <th>
                                         Descripcion del resultado alcanzado <br> en terminos de cantidad, oportunidad,<br> fecha de inicio y finalizacion 
                                    </th>
                                    <th>
                                        Medio de <br> Verificacion
                                    </th>
                                    <th>
                                        Recursos <br> Asignados
                                    </th>   
                                    <th>
                                        Comentarios
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>
                                         1
                                    </td>
                                    <td>
                                         Elaboracion de las especificaciones tecnicas para el sistema un integrado de seguridad...
                                    </td>
                                    <td>
                                        Adjudicacion dek lote N2 del DBC (Equipo Electronico Ultrasonico, Arcos detectores de metales y explosivos, escaner RX...)
                                    </td>
                                    <td>
                                        Contrato Administrativo
                                    </td>
                                    <td>
                                       SI
                                    </td>
                                    <td>
                                        Sin comentarios
                                    </td>   
                                </tr>
                                
                                </tbody>
                                </table>
                            </div>
                            <div class="row">
                                        <div class="col-md-offset-10 col-md-8">
                                            <button type="button" class="btn green">Guardar </button>
                                        </div>
                                    </br></br>
                                </div>
                            </form>
                                    </div>
                                    <div class="tab-pane" id="tab4">
                                        <h3  class="col-md-10" >Capacitacion Recibida en la Gestion</h3>
                                       <form class="form-horizontal" role="form">
                                <div class="form-group">
                                    <label for="inputEmail1" class="col-md-4 control-label">Evento de Capacitacion: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputEmail1" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Descripcion de la forma de aplicacion de los conocimientos adquiridos en el desarrollo de sus funciones: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                 <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Medio de Verificacion: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                <div class="row">
                                        <div class="col-md-offset-5 col-md-8">
                                            <button type="button" class="btn green">Añadir </button>
                                             <button type="button" class="btn green">Nuevo </button>
                                        </div>
                                    </br></br>
                                </div>
                                <div class="table-scrollable">
                                <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>
                                         #
                                    </th>
                                    <th>
                                         Descripcion del Resultado
                                    </th>
                                    <th>
                                         Descripcion de la forma de aplicacion de los <br>conocimientos adquiridos en el desarrollo de sus funciones
                                    </th>
                                    <th>
                                         Medio de Verificacion
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>
                                         1
                                    </td>
                                    <td>
                                         Especialista en sistemas de gestion de la calidad ISO 9001:2008
                                    </td>
                         
                                    <td>
                                        Mejorar los procesos y procedimientos de la unidad
                                    </td>
                                 
                                    <td>
                                        Informes 
                                    </td>   
                                    
                                </tr>
                                </tbody>
                                </table>
                            </div>
                            <div class="row">
                                        <div class="col-md-offset-10 col-md-8">
                                            <button type="button" class="btn green">Guardar </button>
                                        </div>
                                    </br></br>
                                </div>
                            </form>
                                    </div>
                                    <div class="tab-pane" id="tab5">
                                         <h3  class="col-md-10" >Necesidad de Capacitacion </h3>
                                       <form class="form-horizontal" role="form">
                                <div class="form-group">
                                    <label for="inputEmail1" class="col-md-4 control-label">Funciones Principales: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputEmail1" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Denominacion del tema relacionado con la funcion que ayuda a su reforzamiento: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                 <div class="form-group">
                                    <label for="inputPassword12" class="col-md-4 control-label">Profundidad: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputPassword12" placeholder="">
                                    </div>
                                </div>
                                <div class="row">
                                        <div class="col-md-offset-5 col-md-8">
                                            <button type="button" class="btn green">Añadir </button>
                                             <button type="button" class="btn green">Nuevo </button>
                                        </div>
                                    </br></br>
                                </div>
                                <div class="table-scrollable">
                                <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>
                                         #
                                    </th>
                                    <th>
                                         Funciones Principales
                                    </th>
                                    <th>
                                         Denominacion del tema relacionado con <br> la funcion que ayude a su reforzamiento
                                    </th>
                                    <th>
                                         Profundidad
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>
                                         1
                                    </td>
                                    <td>
                                         Gerenciamiento TIC's
                                    </td>
                         
                                    <td>
                                        Curso de alta gerencia en TIC's
                                    </td>
                                 
                                    <td>
                                        Avanzado 
                                    </td>   
                                    
                                </tr>
                                </tbody>
                                </table>
                            </div>
                            <div class="row">
                                        <div class="col-md-offset-10 col-md-8">
                                            <button type="button" class="btn green">Guardar </button>
                                        </div>
                                    </br></br>
                                </div>
                            </form>
                                    </div>
                                    <div class="tab-pane" id="tab6">
                                        <h3  class="col-md-10" >Otros Temas Sugeridos de Interes General </h3>
                                       <form class="form-horizontal" role="form">
                                <div class="form-group">
                                    <label for="inputEmail1" class="col-md-4 control-label">Denominacion del Tema: </label>
                                    <div class="col-md-5">
                                        <input type="text" class="form-control" id="inputEmail1" placeholder="">
                                    </div>
                                </div>
                                
                                <div class="row">
                                        <div class="col-md-offset-5 col-md-8">
                                            <button type="button" class="btn green">Añadir </button>
                                             <button type="button" class="btn green">Nuevo </button>
                                        </div>
                                    </br></br>
                                </div>
                                <div class="table-scrollable">
                                <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>
                                         #
                                    </th>
                                    <th>
                                         Denominacion del Tema
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>
                                         1
                                    </td>
                                    <td>
                                         
                                    </td>
                         
                                    
                                </tr>
                                </tbody>
                                </table>
                            </div>
                            <div class="row">
                                        <div class="col-md-offset-10 col-md-8">
                                            <button type="button" class="btn green">Guardar </button>
                                        </div>
                                    </br></br>
                                </div>

                                <div class="row">
                                        <div class="col-md-offset-4 col-md-8">
                                            
                                            <a class="btn green" data-toggle="modal" href="#basic">
                                   FINALIZAR REGISTRO DE ACTIVIDADES</a>
                                        </div>
                                    </br></br>
                                </div>
                            </form>
                                    </div>
                                </div>
                            </div>
    </div>
</div>

<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="../../assets/global/plugins/respond.min.js"></script>
<script src="../../assets/global/plugins/excanvas.min.js"></script> 
<![endif]-->
<script src="../../assets/global/plugins/jquery.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
<!-- IMPORTANT! Load jquery-ui.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<script src="../../assets/global/plugins/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="../../assets/global/scripts/metronic.js" type="text/javascript"></script>
<script src="../../assets/admin/layout/scripts/layout.js" type="text/javascript"></script>
<script src="../../assets/admin/layout/scripts/quick-sidebar.js" type="text/javascript"></script>
<script src="../../assets/admin/layout/scripts/demo.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script>
jQuery(document).ready(function() {       
   // initiate layout and plugins
   Metronic.init(); // init metronic core components
Layout.init(); // init current layout
QuickSidebar.init(); // init quick sidebar
Demo.init(); // init demo features
  $("#draggable").draggable({
      handle: ".modal-header"
  });
});
</script>
<!-- END JAVASCRIPTS -->