<div class="col-md-10" >
    <h3 > <b> 1.1. Datos del Puesto </b> </h3>
</div>

<form class="form-horizontal" role="form">

    <div class="form-group">
        <label for="text" class="col-md-4 control-label">Nro de Item: </label>
        <div class="col-md-8">
            </br><label for = "denominacion_cargo" id="lab_denominacion_cargo"> 301 </label>
        </div>

        <label for="text" class="col-md-4 control-label">Nivel: </label>
        <div class="col-md-8">
            </br><label for = "denominacion_cargo" id="lab_denominacion_cargo"> 5 </label>
        </div>

        <label for="text" class="col-md-4 control-label">Categoría: </label>
        <div class="col-md-8">
            </br><label for = "denominacion_cargo" id="lab_denominacion_cargo"> OPERATIVO </label>
        </div>

        <label for="text" class="col-md-4 control-label">Denominación del cargo: </label>
        <div class="col-md-8">
            </br><label for = "denominacion_cargo" id="lab_denominacion_cargo"> PROFESIONAL II </label>
        </div>

        <label for="text" class="col-md-4 control-label">Denominacion del puesto: </label>
        <div class="col-md-8">
            </br><label for = "denominacion_puesto" id="lab_denominacion_puesto"> RESPONSABLE DE MOVILIDAD Y REGISTRO DE PERSONAL </label>
        </div>

        <label for="text" class="col-md-4 control-label">Dependencia: </label>
        <div class="col-md-8">
            </br><label for = "dependencia" id="lab_dependencia"> UNIDAD DE RECURSOS HUMANOS</label>
        </div>
    </div>
</form>